### PR TITLE
[DO NOT MERGE] CKB VM performance test

### PR DESCRIPTION
**Pull request by xxuejie**
Please do not merge this.

### CODE REVIEW

**Comment by mohanson** [comment]
You should also update `ckb-vm-definitions`

**Comment by xxuejie** [comment]
benchmark

**Comment by xxuejie** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 228
  - CKB Version: a35e44b2a422be29ded3a92d43f22219c332fc19
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 226
  - CKB Version: a4c14f6322c892832b8dcffae6d1d3557d981601
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by xxuejie** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 144
  - CKB Version: 97524104f0b41c660994787dcc3c064b55459f65
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by quake** [comment]
benchmark, sync-test

**Comment by quake** [comment]
benchmark, sync-test

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 484
  - CKB Version: 80f2fc15c31bd925081db87568fae3bc8676dbcb
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by nervos-bot-user** [comment]
#### Sync Test Result
  - CKB Version: 80f2fc15c31bd925081db87568fae3bc8676dbcb
  - Instance Region: ap-southeast-1
  - Sync Start: 2021-03-13 06:49:19
  - Sync End: 2021-03-13 08:54:32
  - Sync Height: 3943721
  - Sync Speed: 524 blocks/s

**Pull request closed without merging**
