### PR TITLE
test: just open a pr to test automatic benchmark

### PR DESCRIPTION
**Pull request by yangby-cryptape**
**DO NOT MERGE**

### CODE REVIEW

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 294.01
  - Samples Count: 51
  - CKB Version: 80626dde878c085a3999e7e48f6572b499f5b7a5
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
benchmark

**Pull request closed without merging**
