### PR TITLE
chore: upgrade rust toolchain

### PR DESCRIPTION
**Pull request by driftluo**
wait for https://github.com/nervosnetwork/ckb-docker-builder/pull/5

`-A clippy::upper_case_acronyms` Because the modification area is too large, including CKB, DAO, DB, etc.

### CODE REVIEW

**Comment by doitian** [comment]
Todo for me:

* [ ] Fix `gen-rpc-doc`

**Comment by nervos-bot-user** [comment]
Can one of the admins verify this patch?

**Review by zhangsoledad — DISMISSED** [review]
LGTM

**Review by yangby-cryptape — DISMISSED** [review]

**Comment by driftluo** [comment]
bors r=yangby-cryptape,zhangsoledad

**Review by quake — DISMISSED** [review]

**Comment by quake** [comment]
bors r=quake,zhangsoledad,yangby-cryptape

**Review by doitian — APPROVED** [review]

**Comment by driftluo** [comment]
bors r=quake,zhangsoledad,yangby-cryptape,doitian

**Review by yangby-cryptape — APPROVED** [review]

**Review by zhangsoledad — APPROVED** [review]

**Review by quake — APPROVED** [review]

**Review by doitian — APPROVED** [review]

**Comment by driftluo** [comment]
bors r=quake,zhangsoledad,yangby-cryptape,doitian

**Pull request merged**
