### PR TITLE
propose the tx structure changes for discussion

### PR DESCRIPTION
**Pull request by doitian**

### CODE REVIEW

**Comment by quake** [comment]
```rust
pub struct Transaction {
    version: Version,
    cell_deps: Vec<CellDep>,
    header_deps: Vec<H256>,
    inputs: Vec<CellInput>,
    data: Vec<Bytes>,
    outputs: Vec<CellOutput>,
    witnesses: Vec<Vec<Bytes>>,
}

pub struct OutPoint {
    tx_hash: H256,
    index: u32,
}

pub struct CellDep {
    previous_output: OutPoint,
    is_group: bool,
}

pub enum ScriptHashType {
    Data = 0,
    Type = 1,
}

 pub struct Script {
    args: Vec<Bytes>,
    code_hash: H256,
    hash_type: ScriptHashType,
}

 pub struct CellInput {
    previous_output: OutPoint,
    lock_script: Script,
    since: u64,
}

pub struct CellOutput {
    capacity: Capacity,
    lock_hash: H256,
    type_script: Option<Script>,
}
```

**Comment by u2** [comment]
Where is the output data?

**Comment by doitian** [comment]
> CellProperties -> Kernel {capacity, lock, type}, where lock and type are both `Script`.

So we are not going to introduce the feature which reveals the lock script only when the cell is used as an input?

**Comment by janx** [comment]
> > CellProperties -> Kernel {capacity, lock, type}, where lock and type are both `Script`.
> 
> So we are not going to introduce the feature which reveals the lock script only when the cell is used as an input?

If there's no objection, yes. According to our discussion in channel, it seems unnecessary to do that if we're going to move data back into cell.

**Comment by janx** [comment]
Is it better to replace `previous_output` with just `outpoint`?

**Comment by doitian** [comment]
Relates to #1356

**Comment by doitian** [comment]
Final version:

```rust
pub struct Transaction {
    version: Version,

    cell_deps: Vec<CellDep>,
    header_deps: Vec<H256>,

    // Each input has a corresponding Vec<Bytes> in witnesses
    inputs: Vec<Input>,
    witnesses: Vec<Vec<Bytes>>,

    // Each cell has a corresponding output and data in outputs and outputs_data respectively.
    outputs: Vec<Output>,
    outputs_data: Vec<Bytes>,
}

pub struct CellDep {
    out_point: OutPoint,
    is_group: bool,
}

pub struct OutPoint {
    tx_hash: H256,
    index: u32,
}

pub enum ScriptHashType {
    Data = 0,
    Type = 1,
}

pub struct Script {
    args: Vec<Bytes>,
    code_hash: H256,
    hash_type: ScriptHashType,
}

pub struct Input {
    out_point: OutPoint,
    since: u64,
}

pub struct Output {
    capacity: Capacity,
    lock: Script,
    type_: Option<Script>,
}
```

Transaction

**Pull request closed without merging**
