### PR TITLE
feat: move `add_node` / `remove_node` rpc to `Net` module

### PR DESCRIPTION
**Pull request by quake**

### CODE REVIEW

**Comment by doitian** [comment]
bors r=doitian,yangby-cryptape

**Comment by doitian** [comment]
bors r=doitian,yangby-cryptape

**Comment by doitian** [comment]
Please resolve conflicts

**Comment by quake** [comment]
@yangby-cryptape @doitian rebased, please review again

**Comment by doitian** [comment]
bors r=doitian,yangby-cryptape

**Pull request merged**
