### PR TITLE
chore(deps): bump numext-fixed-uint from 1.4.0 to 1.6.0

### PR DESCRIPTION
**Pull request by yangby-cryptape**
Bumps [numext-fixed-uint](https://github.com/cryptape/rust-numext) from 0.1.4 to 0.1.6.

<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/cryptape/rust-numext/blob/v0.1.6/CHANGELOG.md">rust-numext's changelog</a>.</em></p>
<blockquote>

### Major Updates

- Use features to let all structs be optional.
- Should NOT consider hashes as numbers.
  - Add methods to replace numerical methods for hashes.
    - `zero() -> empty()`
    - `is_zero() -> is_empty()`
    - `is_max() -> is_full()`
  - **BREAKING CHANGE** Remove `checked_neg(..)` for hashes.
- Upgrade dependencies.
  - `quote v0.6 -> v1.0`
  - `syn v0.15 -> v1.0`
  - `proc-macro2 v0.4 -> v1.0`
  - Remove dependencies "proc-macro-hack" for crates in the workspace.
    - Update the minimum supported version of rust toolchain to `1.45.0` for the feature: [Stabilizing function-like procedural macros in expressions, patterns, and statements](https://blog.rust-lang.org/2020/07/16/Rust-1.45.0.html#stabilizing-function-like-procedural-macros-in-expressions-patterns-and-statements).
  - Use `thiserror` instead of `failure` since `failure` is officially deprecated.

### Fixed Bugs

- Constructors can not handle short inputs correctly ([#42]).
- `as_fixed_bytes_mut(&mut self)` return an immutable reference ([#42]).
- Avoid trigger [a rustc bug](https://github.com/rust-lang/rust/issues/75533) which causes errors when build with target `wasm32-unknown-unknown` ([#54]).

</blockquote>
</details>

Full commits viewable in [compare view](https://github.com/cryptape/rust-numext/compare/v0.1.4...v0.1.6).

You can trigger a rebase of this PR by commenting `@yangby-cryptape rebase`.

<small>

#### Notice

**The latest rust tool chain is not friendly for old proc-macros (there are a lot of issues, for example: compile errors).**
**But after this PR, we still have few crates depend on very old proc-macros crates: `enum-display-derive` and `wasm-*`.**

</small>

[#42]: https://github.com/cryptape/rust-numext/pull/42
[#54]: https://github.com/cryptape/rust-numext/pull/54

### CODE REVIEW

**Review by doitian — DISMISSED** [review]

**Review by driftluo — APPROVED** [review]

**Comment by driftluo** [comment]
`enum-display-derive` can be removed, `wasm-*` can upgrade

**Comment by driftluo** [comment]
bors r=doitian,driftluo

**Comment by yangby-cryptape** [comment]
Merge branch only to update the file `Cargo.lock` manually.

**Review by doitian — APPROVED** [review]

**Review by driftluo — APPROVED** [review]

**Comment by driftluo** [comment]
bors r=doitian,driftluo

**Review by quake — APPROVED** [review]

**Pull request merged**
