### PR TITLE
[backport](0.35)feat: permit load cell data from memory

### PR DESCRIPTION
**Pull request by zhangsoledad**

### CODE REVIEW

**Review by doitian — APPROVED** [review]

**Comment by doitian** [comment]
benchmark

**Comment by zhangsoledad** [comment]
Error: [dependencies::ckb_logger_service] in <./ckb-bin>
[ END ] Found 1 errors.
Makefile:142: recipe for target 'check-cargotoml' failed
make: *** [check-cargotoml] Error 1
The command "make check-cargotoml" exited with 2.

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 478
  - CKB Version: 37d60d581c6713d3aca1a57018eaea45447ae0b2
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by doitian** [comment]
```diff
diff --git a/Cargo.lock b/Cargo.lock
index 8900023d5..c8a46e1c1 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -365,7 +365,6 @@ dependencies = [
  "ckb-instrument",
  "ckb-jsonrpc-types",
  "ckb-logger",
- "ckb-logger-service",
  "ckb-memory-tracker",
  "ckb-miner",
  "ckb-network",
diff --git a/ckb-bin/Cargo.toml b/ckb-bin/Cargo.toml
index 960540e1a..f39e44a9c 100644
--- a/ckb-bin/Cargo.toml
+++ b/ckb-bin/Cargo.toml
@@ -13,7 +13,6 @@ toml = "0.5"
 crossbeam-channel = "0.3"
 ckb-app-config = { path = "../util/app-config" }
 ckb-logger = { path = "../util/logger" }
-ckb-logger-service = { path = "../util/logger-service" }
 ckb-util = { path = "../util" }
 ckb-types = { path = "../util/types" }
 ckb-jsonrpc-types = { path = "../util/jsonrpc-types" }

```

**Pull request merged**
