### PR TITLE
fix(test): First 11 cellbases have not outputs

### PR DESCRIPTION
**Pull request by keroro520**
https://github.com/nervosnetwork/ckb/pull/1605 did not correctly resolve conflict before merging. Hence it breaks CI for develop-branch. Here comes this PR to fix it.

### CODE REVIEW

**Comment by keroro520** [comment]
`make integration` passed locally.

**Comment by u2** [comment]
bors r=quake,u2

**Comment by u2** [comment]
bors ping

**Comment by u2** [comment]
bors r=quake,u2

**Comment by u2** [comment]
bors r=quake,u2

**Pull request merged**
