### PR TITLE
refactor: replace lock-lru with moka

### PR DESCRIPTION
**Pull request by zhangsoledad**

### CODE REVIEW

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 232
  - CKB Version: 58976b856067158f37bcc0d16d9ba0116495ea23
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 232
  - CKB Version: 1285f252049daee925dd04f38556d9110187667f
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Pull request closed without merging**
