### PR TITLE
chore: format shell files using shfmt

### PR DESCRIPTION
**Pull request by doitian**
### What problem does this PR solve?

Problem Summary: The shell files are not consistent in format.

### What is changed and how it works?

What's Changed:

Format all the shell files using `shfmt` with following options:

- `-ci`: Indent case
- `-i 2`: 2-spaces indentation

Example to format the file `test/run.sh`

```
shfmt -ci -i 2 -w test/run.sh
```

See more details about `shfmt` in https://github.com/mvdan/sh

### Check List

Tests

- Unit test

### Release note

```release-note
None: Exclude this PR from the release note.
```

### CODE REVIEW

**Comment by doitian** [comment]
Conver to Draft to wait on #3336

**Comment by doitian** [comment]
bors d=liya2017,chanhsu001

**Comment by doitian** [comment]
Added @liya2017 @chanhsu001 as reviewers

**Review by zhangsoledad — APPROVED** [review]

**Pull request merged**
