### PR TITLE
chore: replace dns resolver

### PR DESCRIPTION
**Pull request by driftluo**
Replace `resolve` that has not been maintained for a long time

### CODE REVIEW

**Review by doitian — DISMISSED** [review]

**Review by quake — APPROVED** [review]

**Comment by driftluo** [comment]
bors r=quake,doitian

**Comment by driftluo** [comment]
bors retry

**Review by doitian — DISMISSED** [review]

**Review by quake — APPROVED** [review]

**Comment by quake** [comment]
bors try

**Review by doitian — APPROVED** [review]

**Comment by doitian** [comment]
bors r=quake,doitian

**Pull request merged**
