### PR TITLE
feat: support multiple file loggers

### PR DESCRIPTION
**Pull request by yangby-cryptape**
### Features

- Support multiple file loggers in `ckb.toml`.
  For example, the follow configuration will write all `info` logs into `run.log` and `stdout`, all `trace` logs into `trace.log` and `ckb_chain=info` logs into `chain_info.log`:
  ```toml
  [logger]
  filter = "info"
  color = true
  log_to_file = true
  log_to_stdout = true
  [logger.extra.trace]
  filter = "trace"
  [logger.extra.chain_info]
  filter = "off,ckb_chain=info"
  ```
- Support configuring extra file loggers via RPC (in module `Debug`).
  ```shell
  # Add or update a file logger to write `ckb_chain=info` logs into `chain_info.log`.
  curl -H 'content-type: application/json' -d \
      '{ "id": 2, "jsonrpc": "2.0", "method": "set_extra_logger", "params": ["chain_info", {"filter": "off,ckb_chain=info"}] }' \
      http://localhost:8114
  # Remove the file logger `ckb_chain`
  curl -H 'content-type: application/json' -d \
      '{ "id": 2, "jsonrpc": "2.0", "method": "set_extra_logger", "params": ["chain_info", null] }' \
      http://localhost:8114
  ```

### CODE REVIEW

**Comment by quake** [comment]
we may reuse the `set_logger_filter` rpc by adding an optional extra id to it:

```shell
# Add a file logger to write `ckb_chain=info` logs into `chain_info.log`.
curl -H 'content-type: application/json' -d \
    '{ "id": 2, "jsonrpc": "2.0", "method": "set_logger_filter", "params": ["off,ckb_chain=info", "chain_info"] }' \
    http://localhost:8114

# Remove the file logger `ckb_chain`
curl -H 'content-type: application/json' -d \
    '{ "id": 2, "jsonrpc": "2.0", "method": "set_logger_filter", "params": ["", "chain_info"] }' \
    http://localhost:8114

# Updtate the main logger filter
curl -H 'content-type: application/json' -d \
    '{ "id": 2, "jsonrpc": "2.0", "method": "set_logger_filter", "params": ["error,ckb_chain=warn"] }' \
    http://localhost:8114
```

**Comment by yangby-cryptape** [comment]
> we may reuse the `set_logger_filter` rpc by adding an optional extra id to it:

`main logger filter` is not equal to any `multiple file loggers`.

- `set_logger_filter` can add more features in future, but `multiple file loggers` don't support these features.
  For example: toggle output to stdout, toggle color.

- You can not remove the `main logger filter` but you can remove any `multiple file loggers`.
  `""` means no filter or default filter, but `null` means remove/delete.
  So `set_logger_filter` and `set_extra_logger` are two different APIs.

**Comment by quake** [comment]
> * `set_logger_filter` can add more features in future, but `multiple file loggers` don't support these features.
>   For example: toggle output to stdout, toggle color.

As the rpc name suggests, it is only used to modify the logger filter, not all configuration options. Better to rename this rpc to `set_logger_config` if you plan to add more options:

```shell
# Updtate the main logger filter and disable stdout log
curl -H 'content-type: application/json' -d \
    '{ "id": 2, "jsonrpc": "2.0", "method": "set_logger_config", "params": [{"filter": "error,ckb_chain=warn", "log_to_stdout": false}}' \
    http://localhost:8114

# Add an extra file logger to write `ckb_chain=info` logs into `chain_info.log`.
curl -H 'content-type: application/json' -d \
    '{ "id": 2, "jsonrpc": "2.0", "method": "set_logger_config", "params": [{"filter": "off,ckb_chain=info", "extra": "chain_info"}}' \
    http://localhost:8114

# Remove the extra file logger `ckb_chain`
curl -H 'content-type: application/json' -d \
    '{ "id": 2, "jsonrpc": "2.0", "method": "set_logger_config", "params": ["filter": "", "extra": "chain_info"] }' \
    http://localhost:8114
```

**Comment by yangby-cryptape** [comment]
Compare with pseudo-code for the `set_logger_config`:
```
struct Input {
    filter: Option<String>,
    extra: Option<String>,
    log_to_stdout: Option<bool>,
    log_to_file: Option<bool>,
    color: Option<bool>,
}

fn set_logger_config(input: Input) -> Result<(),()> {
    if let Some(extra) =  extra {
        if log_to_stdout.is_some() || log_to_file.is_some() || color.is_some() {
            return Err(()); // Extra logger don't have these options.
        }
        if let Some(filter) = filter {
            ckb_logger::add_extra_logger(extra, filter);
        } else {
            ckb_logger::remove_extra_logger(extra);
        }
    } else if log_to_stdout.is_none() && log_to_file.is_none() && color.is_none() && filter.is_none() {
        return Err(()); // No options has been provided.
    } else {
        if let Some(log_to_stdout) = log_to_stdout {
            ckb_logger::set_default_logger_log_to_stdout(log_to_stdout);
        }
        if let Some(log_to_file) = log_to_file {
            ckb_logger::set_default_logger_log_to_file(log_to_file);
        }
        if let Some(color) = color {
            ckb_logger::set_default_logger_color(color);
        }
        if let Some(filter) = filter {
            ckb_logger::set_default_logger_filter(filter);
        }
    }
}
```

IMHO, I prefer to current version.
At least, you don't have to care about options conflicts.
If the input data could be deserialized, it will be valid, no errors could be raised.

**Comment by yangby-cryptape** [comment]
HOLD because this PR is under discussion.

**Comment by yangby-cryptape** [comment]
bors r=quake,TheWaWaR

**Pull request merged**
