### PR TITLE
A workflow to package

### PR DESCRIPTION
**Pull request by liya2017**
A workflow for package on different os

TODO:

- [ ] Add Github Actions self-hosted runner
- [ ] Add secrets, then retest and refine the related steps
- [ ] Find the ideal location to store the secret.asc which use in windows package step, then need refine the related steps.

### CODE REVIEW

**Comment by nervos-bot-user** [comment]
Can one of the admins verify this patch?

**Comment by nervos-bot-user** [comment]
Can one of the admins verify this patch?

**Comment by doitian** [comment]
Windows can use the same key with Linux

**Review by quake — DISMISSED** [review]

**Comment by quake** [comment]
please check this error
```
Makefile:154: recipe for target 'check-whitespaces' failed
```

**Comment by liya2017** [comment]
> please check this error
> 
> ```
> Makefile:154: recipe for target 'check-whitespaces' failed
> ```

fixed

**Review by quake — DISMISSED** [review]

**Comment by doitian** [comment]
I will test this for v0.43.0-rc1 and merge locally.

**Pull request closed without merging**
