### PR TITLE
fix: fix block transaction process missing remove inflight

### PR DESCRIPTION
**Pull request by driftluo**
fix block transaction process missing remove inflight

### CODE REVIEW

**Comment by driftluo** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
#### Benchmark Result
  - TPS: 296.25
  - Samples Count: 51
  - CKB Version: a5ed8a86e313b4fb4e4d3f352f12f8afe9662ea2
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Comment by driftluo** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
#### Benchmark Result
  - TPS: 297.18
  - Samples Count: 50
  - CKB Version: ed8f48d1b5ec0ef13085ab90d76234e80d83fc88
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Comment by driftluo** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
#### Benchmark Result
  - TPS: 240.02
  - Samples Count: 51
  - CKB Version: 0ed9cac21de7d7426773891d0ba48bd9705b6a2e
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Pull request closed without merging**
