### PR TITLE
test: just open a PR to test automatic benchmark

### PR DESCRIPTION
**Pull request by yangby-cryptape**

### CODE REVIEW

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
Test adding comment to Pull Request via CI

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
#### Benchmark Result
  - TPS = 301.44
  - Samples Count = 50
  - CKB Version = 10dd49324b44a743b185ed921d8b034e9758e1e2
  - Instance Type = c5.xlarge
  - Instances Count = 3
  - Bench Type = 2in2out

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
#### Benchmark Result
  - TPS: 297.55
  - Samples Count: 50
  - CKB Version: 10dd49324b44a743b185ed921d8b034e9758e1e2
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Comment by driftluo** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
#### Benchmark Result
  - TPS: 306.65
  - Samples Count: 50
  - CKB Version: 10dd49324b44a743b185ed921d8b034e9758e1e2
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Comment by yangby-cryptape** [comment]
benchmark

**Pull request closed without merging**
