### PR TITLE
refactor(logger): replace lazy_static with once_cell

### PR DESCRIPTION
**Pull request by zhangsoledad**

### CODE REVIEW

**Review by yangby-cryptape — APPROVED** [review]

**Review by quake — APPROVED** [review]

**Comment by quake** [comment]
bors r=quake,yangby-cryptape

**Comment by doitian** [comment]
bors retry

**Comment by doitian** [comment]
bors retry

**Comment by doitian** [comment]
bors r=quake,yangby-cryptape

**Pull request merged**
