### PR TITLE
CI: Fix CKB command line usage test case by bats-core/bats

### PR DESCRIPTION
**Pull request by eval-exec**
### What problem does this PR solve?

This PR want to enhance test case for ckb command line usage. Related: #3892 
Cc. @quake 
- [x] upgrade `bats-core/bats`, `bats-core/bats-assert` and `bats-core/bats-support`
- [x] fix `*.bats` tests in `util/app-config/src/tests`
- [x] Add a way to run *.bats test in Makefile ( `make cli-test`)

### Related changes

- Upgrade `bats` toolkit version in CI job.
- Fix `ckb list-hashes` and `ckb list-hashes -b` bats test case.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code ci-runs-only: [ quick_checks,linters ]

Side effects

None

### Release note 

```release-note
Title Only: Include only the PR title in the release note.
```

### CODE REVIEW

**Comment by eval-exec** [comment]
- [ ] TODO Add a way to run `*.bats` test in `Makefile`

**Comment by eval-exec** [comment]
I think this PR is ready for review.

**Review by quake — APPROVED** [review]

**Comment by eval-exec** [comment]
There is a CI action which cost 8 hours: https://github.com/nervosnetwork/ckb/actions/runs/4499249342/jobs/7916891732

**Comment by zhangsoledad** [comment]
blocking by https://github.com/nervosnetwork/ckb/pull/3904

**Comment by eval-exec** [comment]
https://github.com/nervosnetwork/ckb/actions/runs/4509147319/jobs/7938569945

Weirdly, CI action failed to copy `target/release/ckb` to `/tmp/ckb_bats_testbed`:

cp: cannot stat 'target/release/ckb': No such file or directory

**Comment by eval-exec** [comment]
CI integration test failed on MacOS (https://github.com/nervosnetwork/ckb/actions/runs/4510071188/jobs/7940588698)

`ERROR ckb_test  ckb-test failed on spec BlockSyncDuplicatedAndReconnect`

**Pull request merged**
