### PR TITLE
[HOLD] test: Add cases of tx_hash collision

### PR DESCRIPTION
**Pull request by keroro520**
Add some test-cases about tx_hash collision.

There are some bugs in txpool, to make the added cases fail to run. But I did not fix that, just comment on the cases.

### CODE REVIEW

**Comment by u2** [comment]
The reason is that these two transactions have the same transaction hash and short_id, but the tx_pool use short_id as hash_map/hash_set key.

https://github.com/nervosnetwork/ckb/blob/develop/tx-pool/src/process/chain_reorg.rs#L145
The two transactions have different `sorted_keys` because the `vbytes` is different.

If one transaction is removed at https://github.com/nervosnetwork/ckb/blob/develop/tx-pool/src/process/chain_reorg.rs#L164 or other places.

https://github.com/nervosnetwork/ckb/blob/develop/tx-pool/src/process/chain_reorg.rs#L146
When we fetch the other transaction, https://github.com/nervosnetwork/ckb/blob/develop/tx-pool/src/process/chain_reorg.rs#L146 it will panic.

I think we should return an error if the later transaction's short_id has a collision with the ones in the transaction pool.

**Comment by keroro520** [comment]
> The reason is that these two transactions have the same transaction hash and short_id, but the tx_pool use short_id as hash_map/hash_set key.
> 
> https://github.com/nervosnetwork/ckb/blob/develop/tx-pool/src/process/chain_reorg.rs#L145
> The two transactions have different `sorted_keys` because the `vbytes` is different.
> 
> If one transaction is removed at https://github.com/nervosnetwork/ckb/blob/develop/tx-pool/src/process/chain_reorg.rs#L164 or other places.
> 
> https://github.com/nervosnetwork/ckb/blob/develop/tx-pool/src/process/chain_reorg.rs#L146
> When we fetch the other transaction, https://github.com/nervosnetwork/ckb/blob/develop/tx-pool/src/process/chain_reorg.rs#L146 it will panic.
> 
> I think we should return an error if the later transaction's short_id has a collision with the ones in the transaction pool.

Out-of-scope of this PR.

**Comment by u2** [comment]
it's the reason for node panic.

**Comment by doitian** [comment]
Hold until we have a fix

**Comment by keroro520** [comment]
Already cherry-picked by #1736

**Pull request closed without merging**
