### PR TITLE
fix: remove useless `epoch_reward` from EpochView in RPC

### PR DESCRIPTION
**Pull request by spartucus**
A fix for #1303.

### CODE REVIEW

**Comment by TheWaWaR** [comment]
You can run `make ci` in your local machine for a quick check if CI can pass.
The full check is `make ci && make integration`.

Also commit message should follow [this convention](https://github.com/commitizen/cz-cli).

**Comment by doitian** [comment]
The problem is in the RPC test. The field must be removed from `rpc/json/rpc.json`, and then regenerate the RPC doc via `make gen-rpc-doc`.

**Comment by spartucus** [comment]
well,  it seems `rebase` make commits worse :(

**Comment by quake** [comment]
> well, it seems `rebase` make commits worse :(

Please rebase with `develop` branch and squash to one commit, thanks.

**Comment by spartucus** [comment]
> Please rebase with develop branch and squash to one commit, thanks.

had to merge updated commits, and rebase & force push.

**Comment by quake** [comment]
> > Please rebase with develop branch and squash to one commit, thanks.
> 
> had to merge updated commits, and rebase & force push.

it seems that you merge the develop branch to your branch, not rebase, could you please check it again?

**Comment by spartucus** [comment]
I re-pull a one request, since this is beyond rebase.

**Pull request closed without merging**
