### PR TITLE
Revert chain_root field

### PR DESCRIPTION
**Pull request by jjyr**
Need more research on light client protocol, revert the `chain_root` for now, we can make a hard-fork to add it back after we decide the light client protocol.

revert https://github.com/nervosnetwork/ckb/pull/1518

### CODE REVIEW

**Comment by u2** [comment]
bors r=doitian,u2

**Comment by doitian** [comment]
@jjyr please resolve conflicts

**Comment by jjyr** [comment]
bors r=doitian,u2

**Comment by u2** [comment]
bors r=doitian,u2

**Comment by jjyr** [comment]
bors r=doitian,u2

**Comment by jjyr** [comment]
bors r=doitian,u2

**Comment by jjyr** [comment]
bors retry

**Comment by jjyr** [comment]
bors r=doitian,u2

**Comment by zmitton** [comment]
Im wondering why this got reverted. Its literally the only consensus changes needed to open up the world of Fly Proofs. 

I imagine the light client protocol will continue to evolve for quite some time after this field of possibilities starts getting explored.

**Comment by janx** [comment]
We did plenty of research then but we got no time to figure out how to handle difficulty adjustment verification (hint: it's more complicated than Bitcoin) as the mainnet is going to launch in Nov. Consider header synchronization is fast in the early stage anyway, we decided not to merge this but leave incorporation of flyclient (or better solutions) to future hardforks.

**Comment by jjyr** [comment]
The details of the light client protocol haven't been fully discussed; the chain_root field could be very different depending on the specific design, this field should be introduced via a hard fork after fully discuss a light protocol design.

**Comment by zmitton** [comment]
One of the problems with "shoe-horning" it in later (even as hard fork) is that a FlyProof will never be able to validate the work back to genesis.

For some background, Im a fan of FlyClient, have implemented MMRs in [JS](https://github.com/zmitton/merkle-mountain-range) and [Golang](https://github.com/zmitton/go-merklemountainrange), and would like to see the technology finally brought live (somewhere or another).

I worked past a lot of potential issues in my head, but am not too familiar with Nervos specifics. Would one of you be willing to chat with me for a few minutes about the chain_root field and difficulty adjustment issues?

**Comment by zmitton** [comment]
Or is there a resource you can point me to? The FlyClient paper specifically tackles difficulty adjustment. 

As for the chain_root question, I'm not sure what the problem could be. If you implement the mmr_root as the hash of concatenated peaks, it can be calculated functionally (on-the-fly) in log(n)/2 time (and not saved anywhere). This allows the entire MMR to be append only. Not sure if that helps 🤷

**Comment by janx** [comment]
We like FlyClient too :smile: 

The difficulty adjustment in CKB depends on the number of uncle blocks in an epoch. You can find the details in [Dynamic Difficulty Adjustment Mechanism section of rfc#0020](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0020-ckb-consensus-protocol/0020-ckb-consensus-protocol.md#Dynamic-Difficulty-Adjustment-Mechanism) (better to read the whole document).

**Comment by zmitton** [comment]
I think as uncles get committed they would just add to the total difficulty at that point. The merkle-sum tree would work as usual. As long as uncles are included in the header, a flyProof would just have to include any referenced uncles.

**Comment by janx** [comment]
There're two problems to solve when we apply FlyClient to CKB:

1. FlyClient assumes fixed epoch length while NC-Max (the consensus algorithm used in CKB) has variable epoch length;
2. FlyClient assumes original NC style difficulty adjustment, which depends only on timestamps of the first block of each epoch, while difficulty adjustment in NC-Max depends on the number of uncles in the last epoch.

I think we need to improve the Variable Difficulty MMR design in FlyClient paper to accommodate NC-Max, probably adding more auxiliary fields to MMR interval/leaf nodes. A Merkle proof for uncle inclusion of sampled nodes is not enough, because at epoch transition the verifier needs to verify the difficulty adjustment is correct, which means verifying the number of uncles in the last epoch is correct. So certain epoch information should be encoded in MMR nodes.

**Pull request merged**
