### PR TITLE
fix typo for hash_type note

### PR DESCRIPTION
**Pull request by DGideas**
Fix a typo for `rpc/README.md`

### CODE REVIEW

**Comment by doitian** [comment]
Could help to update https://github.com/nervosnetwork/ckb/blob/e0c49004c7365f090d7fbbcc80faa0cc92d8824f/util/types/src/core/blockchain.rs#L12 ? The RPC doc is generated from code comments and there is a CI job to ensure they are consistent.

**Comment by DGideas** [comment]
@doitian Okay, I'll update this pr

**Comment by DGideas** [comment]
@doitian updated

**Comment by zhangsoledad** [comment]
> @doitian updated

Ian didn't point out them all, but actually the CI checked here
https://github.com/nervosnetwork/ckb/blob/b27b1ab837ad614beb89ac582daaf3a0839d0473/util/jsonrpc-types/src/blockchain.rs#L24

**Comment by zhangsoledad** [comment]
Great. 
bors r=zhangsoledad

**Pull request merged**
