### PR TITLE
test: add `TransactionScriptsVerifier` fuzz test

### PR DESCRIPTION
**Pull request by quake**
This PR adds 2 fuzzers for ckb-script crate, one is for vm0 version, another is for vm1 version.

### CODE REVIEW

**Comment by doitian** [comment]
Let's kill the empty body PRs. Please explain why we need it and how we use it.

**Comment by quake** [comment]
> Let's kill the empty body PRs. Please explain why we need it and how we use it.

there is a simple `README.md` file in this PR

**Review by doitian — APPROVED** [review]

**Review by zhangsoledad — APPROVED** [review]

**Review by keroro520 — APPROVED** [review]
👍

**Comment by keroro520** [comment]
bors r=doitian,zhangsoledad,keroro520

**Pull request merged**
