### PR TITLE
chore: move `get_fork_block` from test module to chain module

### PR DESCRIPTION
**Pull request by quake**

### CODE REVIEW

**Review by doitian — DISMISSED** [review]

**Comment by quake** [comment]
@doitian rebased with develop, please review again, thanks.

**Comment by quake** [comment]
bors try

**Review by driftluo — APPROVED** [review]

**Review by yangby-cryptape — APPROVED** [review]

**Review by doitian — APPROVED** [review]

**Comment by quake** [comment]
bors r=doitian,driftluo,yangby-cryptape

**Comment by quake** [comment]
```
RUST_BACKTRACE=1 RUST_LOG=ckb-network=error test/run.sh -- --bin ../target/debug/ckb --max-time 1200 -c 1
    Updating crates.io index
 Downloading crates ...
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/im/12.3.4/download`, got 503
```

retry

**Comment by quake** [comment]
bors r=doitian,driftluo,yangby-cryptape

**Pull request merged**
