### PR TITLE
feat: Allow TransactionScriptsVerifier set custom debugger printer

### PR DESCRIPTION
**Pull request by TheWaWaR**
Current `Debugger` only log the output and can not detected by outside.

Here we pass a callback to process debug output.

### CODE REVIEW

**Comment by TheWaWaR** [comment]
Current use case is `ckb-cli` need to print the output of `ckb_debug`.

**Comment by xxuejie** [comment]
In that case I really suggest changing the code to allow plugging in a different debugger instance, the current solution is a little weird

**Comment by TheWaWaR** [comment]
The difficulty is about lifetime + generic + associated type a parameter, I'll have a try.

**Comment by xxuejie** [comment]
Why not just use a Box?

**Pull request merged**
