### PR TITLE
feature: is_better_chain uses first-received policy

### PR DESCRIPTION
**Pull request by u2**

### CODE REVIEW

**Comment by keroro520** [comment]
I think it's tests-required.

**Comment by u2** [comment]
> I think it's tests-required.

The `block_sync_forks` tests it.

**Comment by keroro520** [comment]
> > I think it's tests-required.
> 
> The `block_sync_forks` tests it.

`block_sync_forks` only test sync protocol. I mean we should test relay protocol and miner submission as well(or even more complicated cases).

**Comment by u2** [comment]
> > > I think it's tests-required.
> > 
> > 
> > The `block_sync_forks` tests it.
> 
> `block_sync_forks` only test sync protocol. I mean we should test relay protocol and miner submission as well(or even more complicated cases).

 There are two places to test:
1. block sync
2. block processing, no matter where it comes from, whether from miner or other peers.

And the `compact_block` reconstructing is not caring about the better chain policy.

**Comment by u2** [comment]
@keroro520 updated, please review.

**Comment by quake** [comment]
bors r=keroro520,quake

**Pull request merged**
