### PR TITLE
perf: replace RwLock/Mutex<HashMap/HashSet> with DashMap

### PR DESCRIPTION
**Pull request by quake**

### CODE REVIEW

**Comment by nervos-bot-user** [comment]
Can one of the admins verify this patch?

**Comment by quake** [comment]
benchmark, sync-test

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 489
  - CKB Version: c0dc330debe3dbc21e9574ca914b4dda49a60a20
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by nervos-bot-user** [comment]
#### Sync Test Result
  - CKB Version: c0dc330debe3dbc21e9574ca914b4dda49a60a20
  - Instance Region: ap-southeast-1
  - Sync Start: 2021-05-17 01:49:16
  - Sync End: 2021-05-17 03:42:02
  - Sync Height: 4343845
  - Sync Speed: 642 blocks/s

**Comment by quake** [comment]
sync-test

**Comment by nervos-bot-user** [comment]
#### Sync Test Result
  - CKB Version: 4f0b590e0c452bce22f80d2a67c3f5383739fc13
  - Instance Region: ap-southeast-1
  - Sync Start: 2021-05-18 00:50:26
  - Sync End: 2021-05-18 02:56:13
  - Sync Height: 4351010
  - Sync Speed: 576 blocks/s

**Comment by quake** [comment]
benchmark, sync-test

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 483
  - CKB Version: fa9e65e5d89ce680680fe824cd14971bf7ff0141
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by nervos-bot-user** [comment]
#### Sync Test Result
  - CKB Version: fa9e65e5d89ce680680fe824cd14971bf7ff0141
  - Instance Region: ap-southeast-1
  - Sync Start: 2021-06-14 03:43:37
  - Sync End: 2021-06-14 05:52:29
  - Sync Height: 4547729
  - Sync Speed: 588 blocks/s

**Review by doitian — APPROVED** [review]

**Review by zhangsoledad — APPROVED** [review]

**Comment by quake** [comment]
bors r=doitian,zhangsoledad

**Pull request merged**
