### PR TITLE
perf: replace RwLock/Mutex<HashMap/HashSet> with DashMap

### PR DESCRIPTION
**Pull request by quake**

### CODE REVIEW

**Comment by nervos-bot-user** [comment]
Can one of the admins verify this patch?

**Comment by quake** [comment]
benchmark, sync-test

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 500
  - CKB Version: dfe3e7bf7102bea61c5b1e8d237b2a0e4c9afc92
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by nervos-bot-user** [comment]
#### Sync Test Result
  - CKB Version: dfe3e7bf7102bea61c5b1e8d237b2a0e4c9afc92
  - Instance Region: us-west-1
  - Sync Start: 2021-05-06 09:39:01
  - Sync End: 2021-05-06 11:37:50
  - Sync Height: 4272210
  - Sync Speed: 599 blocks/s

**Comment by quake** [comment]
benchmark, sync-test

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 500
  - CKB Version: ba18c4cb0f4bc5a00ad2e2674ed8df0a062fe6e1
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by nervos-bot-user** [comment]
#### Sync Test Result
  - CKB Version: ba18c4cb0f4bc5a00ad2e2674ed8df0a062fe6e1
  - Instance Region: us-west-1
  - Sync Start: 2021-05-07 01:45:16
  - Sync End: 2021-05-07 03:41:11
  - Sync Height: 4276544
  - Sync Speed: 614 blocks/s

**Comment by quake** [comment]
benchmark, sync-test

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 496
  - CKB Version: 938f613f13917046bcb94d7ceb83d395b38d9b03
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by nervos-bot-user** [comment]
#### Sync Test Result
  - CKB Version: 938f613f13917046bcb94d7ceb83d395b38d9b03
  - Instance Region: us-west-1
  - Sync Start: 2021-05-07 05:11:40
  - Sync End: 2021-05-07 07:12:38
  - Sync Height: 4277330
  - Sync Speed: 589 blocks/s

**Comment by quake** [comment]
benchmark, sync-test

**Comment by nervos-bot-user** [comment]
#### Sync Test Result
  - CKB Version: 938f613f13917046bcb94d7ceb83d395b38d9b03
  - Instance Region: ap-southeast-1
  - Sync Start: 2021-05-08 07:28:02
  - Sync End: 2021-05-08 09:17:13
  - Sync Height: 4284754
  - Sync Speed: 654 blocks/s

**Comment by quake** [comment]
benchmark

**Pull request closed without merging**
