### PR TITLE
refactor: re-export crossbeam-channel

### PR DESCRIPTION
**Pull request by zhangsoledad**
## Description

re-export crossbeam-channel from facade wrapper, unify version specify.
use tilde requirements specify for crossbeam-channel, prevent automate dependency updates.

crossbeam-channel 0.4.3 has UB, may lead to jemalloc deadlock.

```
    frame #0: 0x00007fb34acd5620 libpthread.so.0`__lll_lock_wait + 48
    frame #1: 0x00007fb34accddf3 libpthread.so.0`__pthread_mutex_lock + 227
    frame #2: 0x000056423ada57fc ckb`_rjem_je_malloc_mutex_lock_slow at mutex.h:141:2
    frame #3: 0x000056423ada57f4 ckb`_rjem_je_malloc_mutex_lock_slow at mutex.c:84
    frame #4: 0x000056423ad6e1a8 ckb`_rjem_je_arena_tcache_fill_small at mutex.h:205:4
    frame #5: 0x000056423ad6e1a0 ckb`_rjem_je_arena_tcache_fill_small at arena.c:1261
    frame #6: 0x000056423adc1494 ckb`_rjem_je_tcache_alloc_small_hard at tcache.c:93:2
    frame #7: 0x000056423ad68618 ckb`mallocx at tcache_inlines.h:60:9
    frame #8: 0x000056423ad685e0 ckb`mallocx at jemalloc.c:1709
    frame #9: 0x000056423ad685e0 ckb`mallocx at jemalloc.c:1905
    frame #10: 0x000056423ad685e0 ckb`mallocx at jemalloc.c:2005
    frame #11: 0x000056423ad68324 ckb`mallocx at jemalloc.c:2588
    frame #12: 0x000056423b16a56c ckb`alloc::raw_vec::RawVec$LT$T$C$A$GT$::reserve::h10a313223974a7d1 + 188
    frame #13: 0x000056423b1a25f9 ckb`crossbeam_channel::flavors::array::Channel$LT$T$GT$::with_capacity::had6f123b9bc217e1 + 121
```
https://github.com/crossbeam-rs/crossbeam/pull/533
https://github.com/nervosnetwork/ckb/pull/2235

also crossbeam-channel is not optimize for oneshot case. replace it if it is convenient.

### CODE REVIEW

**Review by yangby-cryptape — APPROVED** [review]

**Review by doitian — APPROVED** [review]

**Review by quake — APPROVED** [review]

**Review by doitian — DISMISSED** [review]

**Comment by doitian** [comment]
@zhangsoledad conflicting: util/logger-service/src/lib.rs

**Review by doitian — APPROVED** [review]

**Review by yangby-cryptape — APPROVED** [review]

**Comment by yangby-cryptape** [comment]
bors merge

**Comment by yangby-cryptape** [comment]
Checks can't completed and bors doesn't work.
Let administrator do merge or force-push to rerun Checks after `git commit --amend`.

**Review by yangby-cryptape — APPROVED** [review]

**Comment by zhangsoledad** [comment]
bors r=doitian,yangby-cryptape

**Pull request merged**
