### PR TITLE
chore: bump rust toolchain from 1.38.0 to 1.41.0

### PR DESCRIPTION
**Pull request by yangby-cryptape**
- Fix clippy warnings for `build.rs`.

### CODE REVIEW

**Comment by driftluo** [comment]
Missing travis and azure ci config

**Comment by yangby-cryptape** [comment]
> Missing travis and azure ci config

:cry: Ok, I will force-push this PR to add those updates.

**Comment by doitian** [comment]
Azure and Travis requires https://github.com/nervosnetwork/ckb-docker-builder to create release binaries

**Comment by zhangsoledad** [comment]
bors r=doitian,zhangsoledad

**Pull request merged**
