### PR TITLE
chore: upgrade rustc to 1.36.0

### PR DESCRIPTION
**Pull request by driftluo**
Upgrade rustc to 1.36.0

### CODE REVIEW

**Comment by doitian** [comment]
docker builder images upgraded

**Comment by driftluo** [comment]
wait #1250

**Comment by doitian** [comment]
Can we also remove the dependency hashdown?

**Comment by driftluo** [comment]
> Can we also remove the dependency hashdown?

We can remove the `fnv` and `hashdown` dependencies, but this should not be made into one pr

**Comment by u2** [comment]
> > Can we also remove the dependency hashdown?
> 
> We can remove the `fnv` and `hashdown` dependencies, but this should not be made into one pr

Agree to remove them both, fast enough.

**Pull request merged**
