### PR TITLE
refactor(storage): use flatbuffer instead of bincode in storage

### PR DESCRIPTION
**Pull request by yangby-cryptape**
#### Associated Issues
- #892
- #1031

#### Description

- I use `flatbuffer`, not `cfb`. We can do it later.

- I copy some code from `ckb-protocol`, not just use it, because:

  - Since the data is from local storage, we can ensure the data format shouldn't be malformed.

    Do `expect(..)` is safety for storage, but not safety for network.

  - I try to split those proto-types into different schemas, classify them according to their usages.

  - If required, we can rewrite proto-types for storage, and don't have to modify proto-types for network.

  - I rewrite some of them.

- I just remove `bincode` from `ckb-store`, but I keep the `bincode` for computing hashes. We can do it later.

- I can't remove `serde` from `ckb-core`, because:

  - https://github.com/nervosnetwork/ckb/blob/99dd90e58283d33ec0229a587fdade39cdf2d50d/chain/src/chain.rs#L58-L60

  - https://github.com/nervosnetwork/ckb/blob/99dd90e58283d33ec0229a587fdade39cdf2d50d/util/instrument/src/import.rs#L69

  - A few log outputs.

  I think we should use [`jsonrpc-types`](https://github.com/nervosnetwork/ckb/tree/99dd90e58283d33ec0229a587fdade39cdf2d50d/util/jsonrpc-types) for importing and exporting jsons and use [`Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html) for log outputs.

  Then we can remove `serde` from `ckb-core`.

#### BREAKING CHANGE

The data format in storage is changed.

### CODE REVIEW

**Comment by doitian** [comment]
This will not be included in v0.15.0. Hold until 0.15.0 RC.

**Comment by yangby-cryptape** [comment]
@keroro520:
I force push after rebase this pr from [commit-3648f80].
Please help me to compare the performance between [commit-3648f80] and [commit-e9d2ac6].

[commit-3648f80]: https://github.com/nervosnetwork/ckb/commit/3648f80
[commit-e9d2ac6]: https://github.com/nervosnetwork/ckb/commit/e9d2ac6

**Comment by yangby-cryptape** [comment]
@keroro520:
I force push after rebase this pr from [commit-3648f80].
Please help me to compare the performance between [commit-3648f80] and [commit-de6a5a8].

[commit-3648f80]: https://github.com/nervosnetwork/ckb/commit/3648f80
[commit-e9d2ac6]: https://github.com/nervosnetwork/ckb/commit/de6a5a8

**Comment by yangby-cryptape** [comment]
@nervos-bot try integration

**Comment by yangby-cryptape** [comment]
@nervos-bot try integration

**Pull request merged**
