### PR TITLE
feat: remove memory cellset

### PR DESCRIPTION
**Pull request by zhangsoledad**
## Issue
memory cellset is useless burden, https://github.com/nervosnetwork/ckb-bench/issues/9 shows it didn't have much effect, but will increasing amounts of memory infinity.

## Proposed Changes
remove memory cellset

### CODE REVIEW

**Comment by quake** [comment]
bors r=driftluo,quake

**Comment by doitian** [comment]
Please rebase

```
   Compiling ckb-snapshot v0.30.1-pre (/home/travis/build/nervosnetwork/ckb/util/snapshot)
error[E0560]: struct `Snapshot` has no field named `cell_set`
  --> util/snapshot/src/lib.rs:88:13
   |
88 |             cell_set: self.cell_set.clone(),
   |             ^^^^^^^^ `Snapshot` does not have this field
   |
   = note: available fields are: `tip_header`, `total_difficulty`, `epoch_ext`, `store`, `proposals`, `consensus`
error[E0609]: no field `cell_set` on type `&Snapshot`
  --> util/snapshot/src/lib.rs:88:28
   |
88 |             cell_set: self.cell_set.clone(),
   |                            ^^^^^^^^ unknown field
   |
   = note: available fields are: `tip_header`, `total_difficulty`, `epoch_ext`, `store`, `proposals`, `consensus`
error: aborting due to 2 previous errors
```

**Comment by zhangsoledad** [comment]
resolved

**Comment by yangby-cryptape** [comment]
bors r=quake,driftluo,yangby-cryptape

**Comment by zhangsoledad** [comment]
bors retry

**Pull request merged**
