### PR TITLE
fix: header verifier with wrong header resolver

### PR DESCRIPTION
**Pull request by u2**
https://github.com/nervosnetwork/ckb/blob/develop/verification/src/block_verifier.rs#L161-L173
https://github.com/nervosnetwork/ckb/blob/develop/sync/src/types.rs#L786
https://github.com/nervosnetwork/ckb/blob/develop/sync/src/types.rs#L811

Should find parent from header_map firstly, otherwise, it may not find the parent and lead to the UnknownParent.

todo:
- [ ] add test

### CODE REVIEW

**Comment by keroro520** [comment]
@nervos-bot-user try integration

**Comment by u2** [comment]
bors give me five

**Pull request merged**
