### PR TITLE
refactory resolve transaction

### PR DESCRIPTION
**Pull request by zhangsoledad**
## Description
* short-circuit resolve transaction
* refactory orphan tx pool
* refactory  tx-pool submit interface

### CODE REVIEW

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by yangby-cryptape** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 391
  - CKB Version: d5a6302cbdc6ed0392e0241d877dedbda5b67ee6
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Pull request closed without merging**
