### PR TITLE
feat: monitor rocksdb memory usages in logs (optional; default: disable)

### PR DESCRIPTION
**Pull request by yangby-cryptape**
[Set `memory_tracker.interval` to be a non-zero number in the configuration file](https://github.com/nervosnetwork/ckb/blob/22829ae/docs/ckb-debugging.md#tracking-memory-usage-in-logs) and restart CKB, then we can monitor RocksDB memory usages in logs, without re-compile the binary.

Ref: [RocksDB: Memory usage in RocksDB](https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB)

### CODE REVIEW

**Comment by doitian** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 362.55
  - Samples Count: 51
  - CKB Version: acd190443da4682845bf6d68b43ba74e79eb9a15
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Comment by yangby-cryptape** [comment]
`hold` because @quake had some advices, I will `unhold` this PR after the end of our discussion.

**Comment by doitian** [comment]
> `hold` because @quake had some advices, I will `unhold` this PR after the end of our discussion.

Any progress?

**Comment by yangby-cryptape** [comment]
bors r=quake,driftluo

**Comment by doitian** [comment]
Memo: this logs does not cover indexer db.

**Pull request merged**
