### PR TITLE
fix: fix construct_uncle in integration test

### PR DESCRIPTION
**Pull request by u2**
Fix panic of ForksContainSameUncle. The reason is that the uncle block has the same hash with the main chain block.

### CODE REVIEW

**Comment by u2** [comment]
> I don't get the reason why the generated uncle block has the same hash with the main chain block?
> As I understand, if two blocks have the same hash value, then their heights and timestamp should be the same too; but the problem is when the uncle and main-block have the same height, [`UncleVerifier` should report `UnclesError::InvalidNumber`](https://github.com/nervosnetwork/ckb/blob/9c60a0f00d8a7ba82e87cc2f0553e5df467619aa/verification/src/uncles_verifier.rs#L92) but not `UnclesError::DoubleInclusion`.
> 
> Could you please give an example?

```
    //                     /-> A(U)
    // genesis -> 1 -> 2 ->
    //             \       \-> B(U)
    //              \-> U
```
The problem is that uncle `U` has the same timestamep with block `2`. If you print out the timestamps of uncle block and the  node_a's next block, you will find that the timestamp is very near. 

In my local computer

```
[2019-10-09T01:35:35Z INFO  ckb_test::specs::sync::chain_forks] timestamp 1570584935849
[2019-10-09T01:35:35Z INFO  ckb_test::node] bv.timestamp 1570584935843
```
They are easily collisional.

If you modify this part of code 
https://github.com/nervosnetwork/ckb/blob/develop/test/src/specs/sync/chain_forks.rs#L586-L589

```
        info!("(1) Construct an uncle before fork point");
        let uncle = construct_uncle(node_a);
        node_a.generate_block();
        node_b.generate_block();
```
and make the `uncle` and `node_a.generate_block()` have the same timestamps, the `UnclesError::DoubleInclusion` error will always occur.

**Comment by doitian** [comment]
It is better to add an ID in the cellbase witness instead of relying on different timestamps.

**Comment by u2** [comment]
bors r-

will conflict with https://github.com/nervosnetwork/ckb/pull/1684

**Comment by u2** [comment]
bors r=quake,keroro520

**Pull request merged**
