### PR TITLE
chore: remove hashbrown

### PR DESCRIPTION
**Pull request by u2**
https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html#a-new-hashmapk,-v%3E-implementation

### CODE REVIEW

**Comment by u2** [comment]
And fnv?

**Comment by jjyr** [comment]
> And fnv?

IMO it should be removed too, I guess the performance improvement in our scenario is trivial https://cglab.ca/~abeinges/blah/hash-rs/

**Comment by doitian** [comment]
@nervos-bot-user dummy ci 51985d998419905601c36edbce502097474f4694

**Pull request merged**
