### PR TITLE
chore(ci): Do not send integration test failures in forks.

### PR DESCRIPTION
**Pull request by doitian**

### CODE REVIEW

**Review by chuijiaolianying — DISMISSED** [review]

**Review by keroro520 — DISMISSED** [review]

**Comment by doitian** [comment]
bors r=keroro520,chuijiaolianying

**Comment by doitian** [comment]
Blocked by #2264

**Comment by doitian** [comment]
Rebased

**Review by chuijiaolianying — APPROVED** [review]

**Review by yangby-cryptape — APPROVED** [review]

**Review by keroro520 — APPROVED** [review]

**Review by quake — APPROVED** [review]

**Comment by quake** [comment]
bors r=quake,keroro520,chuijiaolianying,yangby-cryptape

**Pull request merged**
