### PR TITLE
refactor: replace legacy lru-cache

### PR DESCRIPTION
**Pull request by zhangsoledad**
We forked `lru-cache` cause we need such `peek` function, `lru` seems a good alternative.

### CODE REVIEW

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 460
  - CKB Version: 7eff4a00268f2e24e531cee71cf5b59e1f5af2e9
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 424
  - CKB Version: 7eff4a00268f2e24e531cee71cf5b59e1f5af2e9
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 466
  - CKB Version: 7eff4a00268f2e24e531cee71cf5b59e1f5af2e9
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Review by yangby-cryptape — APPROVED** [review]

**Review by doitian — APPROVED** [review]

**Comment by doitian** [comment]
bors r=doitian,yangby-cryptape

**Comment by yangby-cryptape** [comment]
Failed to merge since there was timeouts when downloading rust in CI.

**Comment by yangby-cryptape** [comment]
bors retry

**Pull request merged**
