### PR TITLE
doc: add link to rpc proxy projects

### LINKED ISSUE #3513: Nginx API Gateway examples
#### Is your feature request related to a problem? Please describe.

As said in the [[CKB RPC document](https://github.com/nervosnetwork/ckb/tree/develop/rpc)](https://github.com/nervosnetwork/ckb/tree/develop/rpc),

> Allowing arbitrary machines to access the JSON-RPC port (using the `rpc.listen_address` configuration option) is dangerous and strongly discouraged. Please strictly limit the access to only trusted machines.

But there's no documents about how to configure the RPC access control.

#### Describe the solution you'd like

This issue asks for example configurations of the API gateway for CKB. Except the popular gateway Nginx, it's also welcome to contribute examples for other gateways such as Caddy.

The recommended scenarios for the examples:

- How to limit access by source IP.
- How to set up simple HTTP basic auth.
- How to limit access by RPC method.
- How to throttle the RPC requests.
- Basic gotchas, for example, the default body size is not enough to submit a fully packaged block.

### PR DESCRIPTION
**Pull request by doitian**
### What problem does this PR solve?

Issue Number: close #3513

### What is changed and how it works?

What's Changed:

Add the link to a GitHub topic as mentioned in the issue <https://github.com/nervosnetwork/ckb/issues/3513>

### Check List

Tests

- Integration test: CI that covers RPC doc generation

### Release note

```release-note
None: Exclude this PR from the release note.
```

### CODE REVIEW

**Review by eval-exec — APPROVED** [review]

**Comment by doitian** [comment]
@chenyukang what's the workflow to update RPC doc?

**Comment by chenyukang** [comment]
please run `make gen-rpc-doc` in your local, I expect there is diff after run this command. 
then please run `git add .` and commit & push.

I will deprecate our current flow of adding commit-sha to README.md, it will cause a lot of confusion.

**Comment by doitian** [comment]
I ran locally and only the submodule nervosnetwork/ckb-rpc-resources has updated. What's next? Should I send PR to that repo first?

**Comment by chenyukang** [comment]
no, you only need to work as before, in ckb repo `git add .` and then commit and push.

**Comment by chenyukang** [comment]
I'm removing the submodule of `ckb_rpc_openrpc`, please remove `develop` later :)

**Review by chenyukang — APPROVED** [review]

**Pull request merged**
