### PR TITLE
chore: Expand macros in calc_hash

### PR DESCRIPTION
**Pull request by keroro520**
I would like the frequently used APIs can be auto-completed by IDE. So I expand the macro `impl_calc_special_hash_for_entity` in `calc_hash.rs`

### CODE REVIEW

**Comment by yangby-cryptape** [comment]
I have read all methods in `ckb-core`.

Almost all `getter` method return the field like it's function name, **but some are not, they have different logic, not a simple getter as expected**.

I accept all opinions why we shouldn't use macros.

**But, can you promise that no one will make mistakes and no one will break the rules those have no lints, again?**
An editor feature and correctness, which is important?

If I expand all macros, it also makes my workload looks more heavy.
But I can not promise I will never make mistakes when I wrote so many code, so I use macros.

Maybe you should write a better editor plugin.

**Comment by doitian** [comment]
It seems we need voting here.

**Comment by doitian** [comment]
Please add an emoji reaction here if you support to expand the macros in this PR.

**Comment by doitian** [comment]
Please add an emoji reaction here if you reject the changes in this PR.

**Comment by keroro520** [comment]
> I have read all methods in `ckb-core`.
> 
> Almost all `getter` method return the field like it's function name, **but some are not, they have different logic, not a simple getter as expected**.
> 
> I accept all opinions why we shouldn't use macros.
> 
> **But, can you promise that no one will make mistakes and no one will break the rules those have no lints, again?**
> An editor feature and correctness, which is important?
> 
> If I expand all macros, it also makes my workload looks more heavy.
> But I can not promise I will never make mistakes when I wrote so many code, so I use macros.
> 
> Maybe you should write a better editor plugin.

1. This PR expands `impl_calc_special_hash_for_entity ` inside `calcl_hash.rs`. So I think to discuss the other macros, like getter/setter, is out of the scope of this PR.

2. The reason I open this PR is that it took me some time to figure out "how can I get the lock-hash of a lock-script" when I try to upgrade `ckb-bench`. Compare to the time I had spent 
 to expand `impl_calc_special_hash_for_entity`, the time I spent to look for [`Script::calc_script_hash`](https://github.com/nervosnetwork/ckb/blob/develop/util/types/src/extension/calc_hash.rs#L53) is longer.

3. Now I learn I should always open cargo doc during coding. So it is OK for me that keep this macro.

**Comment by doitian** [comment]
We'll just merge it when it succeeds to collect two approvals.

**Comment by keroro520** [comment]
Close since it is unnecessary.

**Pull request closed without merging**
