### PR TITLE
feat: update ckb-vm to 0.20.0-rc4

### PR DESCRIPTION
**Pull request by mohanson**
ckb-vm 0.20.0-rc3 -> 0.20.0-rc4

```release-note
ckb-vm 0.20.0-rc4 release note: https://github.com/nervosnetwork/ckb-vm/releases/tag/0.20.0-rc4
```

### CODE REVIEW

**Review by quake — APPROVED** [review]

**Comment by mohanson** [comment]
CI Security_Audit_Licenses failed, follow the suggestion to upgrading crossbeam-deque to 0.8.1

```
error[A001]: Data race in crossbeam-deque
    ┌─ /home/runner/work/ckb/ckb/Cargo.lock:122:1
    │
122 │ crossbeam-deque 0.8.0 registry+https://github.com/rust-lang/crates.io-index
    │ --------------------------------------------------------------------------- security vulnerability detected
    │
    = ID: RUSTSEC-2021-0093
    = Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0093
    = In the affected version of this crate, the result of the race condition is that one or more tasks in the worker queue can be popped twice instead of other tasks that are forgotten and never popped. If tasks are allocated on the heap, this can cause double free and a memory leak. If not, this still can cause a logical bug.
      
      Crates using `Stealer::steal`, `Stealer::steal_batch`, or `Stealer::steal_batch_and_pop` are affected by this issue.
      
      Credits to @kmaork for discovering, reporting and fixing the bug.
 advisories FAILED: 1 errors, 3 warnings, 1 notes
        sources ok: 0 errors, 0 warnings, 0 notes
    = Announcement: https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-pqqp-xmhj-wgcw
    = Solution: Upgrade to >=0.7.4, <0.8.0 OR >=0.8.1
```

**Comment by driftluo** [comment]
rebase dev is enough @mohanson

**Comment by doitian** [comment]
Please rebase.

**Comment by mohanson** [comment]
Rebased

**Review by doitian — APPROVED** [review]

**Comment by doitian** [comment]
bors r=quake,doitian

**Pull request merged**
