### PR TITLE
feat: Handle non determinism tests

### PR DESCRIPTION
**Pull request by keroro520**
* feat(test): Add a new setup, `retry_failed`, to specify the retry times when failed.
 
* feat(test): Add env var `CKB_TEST_SEC_COEFFICIENT`, then `utils::sleep(5s)` is equal to `thread::sleep(5 * CKB_TEST_SEC_COEFFICIENT)`

* chore(CI): Run CI with 4 concurrencies.

### CODE REVIEW

**Comment by keroro520** [comment]
bors try

**Comment by keroro520** [comment]
bors try

**Comment by keroro520** [comment]
try integration

**Comment by keroro520** [comment]
@nervos-bot-user try integration

**Comment by doitian** [comment]
bors r=quake,doitian

**Pull request merged**
