### PR TITLE
refactor(tests): simplify several construction functions and double ckb script tests

### PR DESCRIPTION
**Pull request by yangby-cryptape**
_Fix the issue posted by @doitian in https://github.com/nervosnetwork/ckb/pull/2756#discussion_r661130159._

_The best way to review this PR is reviewing each commits._

### Changes

- refactor: simplify vm construction functions which based on versions

  Before this commit, constructing a core vm requires complicated arguments:

  ```rust
  #[cfg(has_asm)]
  let v0_asm_machine = AsmCoreMachine::new(ISA_IMC, VERSION0, max_cycles);

  #[cfg(not(has_asm))]
  let v1_not_asm_machine = DefaultCoreMachine::<u64, WXorXMemory<SparseMemory<u64>>>::new(
      ISA_IMC | ISA_B | ISA_MOP,
      VERSION1,
      u64::max_value(),
  );
  ```

  After this commit, no longer care about cargo features, CKB VM versions or IMC sets:

  ```rust
  let v0_asm_machine = ScriptVersion:V0.init_core_machine(max_cycles);

  let v1_not_asm_machine = ScriptVersion::V1.init_core_machine_without_limit();
  ```

- refactor(tests): simplify tx script verify construction functions

  Before this commit, verifying requires complicated arguments:

  ```rust
  let fork_at = 10;
  let store = new_store();
  let data_loader = DataLoaderWrapper::new(&store);
  let hardfork_switch = HardForkSwitch::new_without_any_enabled()
      .as_builder()
      .rfc_pr_0237(fork_at)
      .rfc_pr_0234(fork_at)
      .build()
      .unwrap();
  let consensus = ConsensusBuilder::default()
      .hardfork_switch(hardfork_switch)
      .build();
  let tx_env0 = {
      let epoch = EpochNumberWithFraction::new(0, 0, 1);
      let header = HeaderView::new_advanced_builder()
          .epoch(epoch.pack())
          .build();
      TxVerifyEnv::new_commit(&header)
  };
  let tx_env1 = {
      let epoch = EpochNumberWithFraction::new(fork_at, 0, 1);
      let header = HeaderView::new_advanced_builder()
          .epoch(epoch.pack())
          .build();
      TxVerifyEnv::new_commit(&header)
  };

  let v0_result = TransactionScriptsVerifier::new(&rtx, &consensus, &data_loader, &tx_env0).verify(100_000_000);
  let v1_result = TransactionScriptsVerifier::new(&rtx, &consensus, &data_loader, &tx_env1).verify(100_000_000);
  ```

  After this commit, no longer care about store, consensus or tx-env:

  ```rust
  let verifier = TransactionScriptsVerifierWithEnv::new();
  let v0_result = verifier.verify_without_limit(ScriptVersion::V0, &rtx);
  let v1_result = verifier.verify_without_limit(ScriptVersion::V1, &rtx);
  ```

  For customize verification rules, try the follow method:
  ```rust
  fn verify_map<R, F>(
      &self,
      version: ScriptVersion,
      rtx: &ResolvedTransaction,
      mut verify_func: F,
  ) -> R
  where
      F: FnMut(TransactionScriptsVerifier<'_, DataLoaderWrapper<'_, ChainDB>>) -> R;
  ```

- test: add more unit tests

  - test: test both vm version 0 and vm version 1 for all syscalls

  - test: test both ckb 2019 and ckb 2021 for ckb script features

  Before this PR, old features are only tested for version 0 and new features are only tested for version 1.

### CODE REVIEW

**Review by zhangsoledad — CHANGES_REQUESTED** [review]
I'm surprised all unit tests be moved to `tests/`, not `src/tests/`.

https://doc.rust-lang.org/book/ch11-03-test-organization.html#unit-tests
https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests

Integration tests are entirely external, so many visibility scopes of internal types need to change, such as https://github.com/nervosnetwork/ckb/pull/2802/files#diff-21f5964eb821ea56c22dce5e0a54cb2237d970d9506a0b20224b716c6f5d8b4cR88-R160, it's meaningless.

**Comment by yangby-cryptape** [comment]
> I'm surprised all `syscalls` unit tests be moved to `tests/`, not `src/tests/`.
> 
> ... ... (omitted)

@zhangsoledad Resolved!

I moved `tests` out of  `src`, because I tried using `features` to control the versions at first.

But after failed, I forgot to move the code back. 😵 

```toml
[[test]]
name = "vm_version_0_syscalls_1"
src = "tests/syscalls_1.rs"
features = ["test_vm_version_v0"]

[[test]]
name = "vm_version_1_syscalls_1"
src = "tests/syscalls_1.rs"
features = ["test_vm_version_v1"]
```

```rust
#[cfg(feature = "test_vm_version_v0")]
const SCRIPT_VERSION: crate::ScriptVersion = crate::ScriptVersion::V0;
#[cfg(feature = "test_vm_version_v1")]
const SCRIPT_VERSION: crate::ScriptVersion = crate::ScriptVersion::V1;

#[tests]
fn test_func_abc () {
    let machine = SCRIPT_VERSION.init_core_machine_without_limit();

   ... ... /* omitted */
}
```

**Review by quake — DISMISSED** [review]

**Review by quake — APPROVED** [review]

**Review by driftluo — APPROVED** [review]

**Comment by yangby-cryptape** [comment]
bors r=quake,driftluo

**Review by zhangsoledad — APPROVED** [review]

**Comment by yangby-cryptape** [comment]
bors r=quake,driftluo,zhangsoledad

**Pull request merged**
