### PR TITLE
Fix dependency `hermit-abi` yanked

### PR DESCRIPTION
**Pull request by eval-exec**
### What problem does this PR solve?

Fix hermit-abi yanked, reported by [security-audit](https://github.com/nervosnetwork/ckb/actions/runs/5462479954/jobs/9941907370?pr=4059) check.

What's Changed:

### Related changes

- Upgrade hermit-abi 

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code ci-runs-only: [ quick_checks,linters ]

Side effects

- None

### Release note 

```release-note
None: Exclude this PR from the release note.
```

### CODE REVIEW

**Comment by driftluo** [comment]
I think we can upgrade `ipnet` to remove this crate

**Comment by eval-exec** [comment]
> I think we can upgrade `ipnet` to remove this crate

Ok, I'm trying.

**Comment by driftluo** [comment]
> > I think we can upgrade `ipnet` to remove this crate
> 
> I tried, upgrade `ipnet` can't remove `hermit-abi`.

it can only upgrade `num_cpus` to remove 0.2.x `hermit-abi` :(

**Comment by zhangsoledad** [comment]
```
cargo update -p num_cpus
    Updating crates.io index
    Removing hermit-abi v0.2.6
    Updating num_cpus v1.15.0 -> v1.16.0
```

**Comment by eval-exec** [comment]
> ```shell
> cargo update -p num_cpus
>     Updating crates.io index
>     Removing hermit-abi v0.2.6
>     Updating num_cpus v1.15.0 -> v1.16.0
> ```

update `num_cpus` only remove `hermit-abi@0.2.6`, but it's the `hermit-abit@0.3.1` result the security audit error:
```
❯ cargo update -p num_cpus

    Updating `tuna` index
    Removing hermit-abi v0.2.6
    Updating num_cpus v1.15.0 -> v1.16.0
ckb on  exec/fix-hermit-abi-yanked is 📦 v0.112.0-pre via 🦀 v1.67.1 via ❄️  impure (nix-shell)
❯ make security-audit
cargo deny check --hide-inclusion-graph --show-stats advisories sources
warning[unmaintained]: `net2` crate has been deprecated; use `socket2` instead
    ┌─ /home/exec/Projects/github.com/nervosnetwork/ckb/Cargo.lock:267:1
    │
267 │ net2 0.2.37 registry+https://github.com/rust-lang/crates.io-index
    │ ----------------------------------------------------------------- unmaintained advisory detected
    │
    = ID: RUSTSEC-2020-0016
    = Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0016
    = The [`net2`](https://crates.io/crates/net2) crate has been deprecated
      and users are encouraged to considered [`socket2`](https://crates.io/crates/socket2) instead.
    = Announcement: https://github.com/deprecrated/net2-rs/commit/3350e3819adf151709047e93f25583a5df681091
    = Solution: No safe upgrade is available!

error[yanked]: detected yanked crate
    ┌─ /home/exec/Projects/github.com/nervosnetwork/ckb/Cargo.lock:204:1
    │
204 │ hermit-abi 0.3.1 registry+https://github.com/rust-lang/crates.io-index
    │ ---------------------------------------------------------------------- yanked version

 advisories FAILED: 1 errors, 1 warnings, 1 notes
        sources ok: 0 errors, 0 warnings, 0 notes
make: *** [Makefile:188: security-audit] Error 1
```

**Review by zhangsoledad — APPROVED** [review]

**Pull request merged**
