### PR TITLE
doc: update RFC links

### PR DESCRIPTION
**Pull request by doitian**
* Update RFC links for ckb2021 features.
* Use rfc232 instead of 237 as the switcher name for the VM versions selection.
* Use master branch for old RFC links.

### CODE REVIEW

**Review by yangby-cryptape — APPROVED** [review]

**Review by yangby-cryptape — CHANGES_REQUESTED** [review]
https://github.com/nervosnetwork/ckb/blob/24038734a495feb6bd72dc5de7aa397b12dd0195/resource/specs/dev.toml#L104

**Comment by doitian** [comment]
> https://github.com/nervosnetwork/ckb/blob/24038734a495feb6bd72dc5de7aa397b12dd0195/resource/specs/dev.toml#L104

Resolved

**Review by yangby-cryptape — DISMISSED** [review]

**Comment by yangby-cryptape** [comment]
```diff
--- a/docs/hashes.toml
+++ b/docs/hashes.toml
@@ -134,7 +134,7 @@ index = 1
 
 # Spec: ckb_dev
 [ckb_dev]
-spec_hash = "0x08240fdc25a2c62c3de7e172dc7d3a2a2ff050b40e54cc20df3e140509ebc518"
+spec_hash = "0xee8912acecf5f17dc044a70b9c83677a23bd8942a263c7c9b222cb1259ddaf3d"
 genesis = "0x823b2ff5785b12da8b1363cac9a5cbe566d8b715a4311441b119c39a0367488c"
 cellbase = "0xa563884b3686078ec7e7677a5f86449b15cf2693f3c1241766c6996f206cc541"
```

**Comment by yangby-cryptape** [comment]
ping @doitian.

**Comment by doitian** [comment]
> ```diff
> --- a/docs/hashes.toml
> +++ b/docs/hashes.toml
> @@ -134,7 +134,7 @@ index = 1
>  
>  # Spec: ckb_dev
>  [ckb_dev]
> -spec_hash = "0x08240fdc25a2c62c3de7e172dc7d3a2a2ff050b40e54cc20df3e140509ebc518"
> +spec_hash = "0xee8912acecf5f17dc044a70b9c83677a23bd8942a263c7c9b222cb1259ddaf3d"
>  genesis = "0x823b2ff5785b12da8b1363cac9a5cbe566d8b715a4311441b119c39a0367488c"
>  cellbase = "0xa563884b3686078ec7e7677a5f86449b15cf2693f3c1241766c6996f206cc541"
> ```

Thanks. I have ran tests locally and the PR should be ready now.

**Review by yangby-cryptape — APPROVED** [review]

**Review by driftluo — APPROVED** [review]

**Review by quake — APPROVED** [review]

**Comment by yangby-cryptape** [comment]
bors merge=yangby-cryptape,driftluo,quake

**Pull request merged**
