### PR TITLE
chore: use minimal cache in Travis CI

### PR DESCRIPTION
**Pull request by doitian**

### CODE REVIEW

**Comment by doitian** [comment]
bors try

**Comment by doitian** [comment]
25 minutes look good to me

- https://travis-ci.com/nervosnetwork/ckb/builds/122408298
- https://travis-ci.com/nervosnetwork/ckb/builds/122408202

**Comment by doitian** [comment]
bors try

**Comment by u2** [comment]
I think we can keep the cache of Linters. Before I have tried to improve the Tests, it's a bit of a dilemma, but it improved for the Linters.

**Comment by doitian** [comment]
Debug integration test only takes 30 minutes.

**Comment by doitian** [comment]
bors retry

**Pull request merged**
