### PR TITLE
perf: remove extremely slow fee_estimator

### PR DESCRIPTION
**Pull request by zhangsoledad**

### CODE REVIEW

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 351.82
  - Samples Count: 50
  - CKB Version: a740340bdda8c306cc557cabeb2da71eb3f36e50
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 356.21
  - Samples Count: 50
  - CKB Version: c002754015399463d6081c2cbb83c44efa4a72b7
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Pull request closed without merging**
