### PR TITLE
chore(test): Allow CI debug logs

### PR DESCRIPTION
**Pull request by keroro520**
The number of logs is acceptable after #1474.

### CODE REVIEW

**Comment by zhangsoledad** [comment]
bors r=u2,zhangsoledad

**Comment by quake** [comment]
bors r=u2,zhangsoledad

**Comment by doitian** [comment]
bors r=u2,zhangsoledad p=10

**Comment by doitian** [comment]
bors r=u2,zhangsoledad p=10

**Comment by doitian** [comment]
bors r=u2,zhangsoledad p=10

**Pull request merged**
