### PR TITLE
feat: prepend the binary version to BlockAssemblerConfig message

### PR DESCRIPTION
**Pull request by quake**

### CODE REVIEW

**Comment by yangby-cryptape** [comment]
Do we have to add an argument for `ckb init`?

**Comment by quake** [comment]
I don't want the user to set this parameter during init, if they want to remove the message_prefix, they need to edit ckb.toml and set it to "0x".

How about adding a commented out line in the generated ckb.toml file?
```
# A message prefix used to identify the miner client, miner can disable this prefix by setting it to empty hex string: "0x".
# messsage_prefix = "0x"
```

**Review by yangby-cryptape — APPROVED** [review]
Looks good.

<details><summary>Only one trivial issue: should we add a separator?</summary>

If a user set the `message` as follow:
```toml
message = "Mined by Xxx."
```
The real message will be `"ckb 0.44.0-pre (337b520 2021-07-12)Mined by Xxx."`.

```rust
        let message = config.message_prefix.as_ref().map_or_else(
            || config.message.as_bytes().pack(),
            |prefix| {
                [prefix.as_bytes(), config.message.as_bytes()]
                    .concat()
                    .pack()
            },
        );
```

So maybe he/she should set the message as follow to make the message more readable with default prefix:
```toml
message = "; Mined by Xxx."
```

</details>

**Comment by keroro520** [comment]
> I don't want the user to set this parameter during init, if they want to remove the message_prefix, they need to edit ckb.toml and set it to "0x".
> 
> How about adding a commented out line in the generated ckb.toml file?
> 
> ```
> # A message prefix used to identify the miner client, miner can disable this prefix by setting it to empty hex string: "0x".
> # messsage_prefix = "0x"
> ```

The name `message_prefix` is too general. Its purpose is to attach the binary version to cellbase witnesses. It is difficult for me to connect the field's name to its purpose.

`cellbase.lock` may want the extra message to appear on the suffix. Their custom `block_assembler.message` is 1st.

**Comment by keroro520** [comment]
> > I don't want the user to set this parameter during init, if they want to remove the message_prefix, they need to edit ckb.toml and set it to "0x".
> > How about adding a commented out line in the generated ckb.toml file?
> > ```
> > # A message prefix used to identify the miner client, miner can disable this prefix by setting it to empty hex string: "0x".
> > # messsage_prefix = "0x"
> > ```
> 
> The name `message_prefix` is too general. Its purpose is to attach the binary version to cellbase witnesses. It is difficult for me to connect the field's name to its purpose.
> 
> `cellbase.lock` may want the extra message to appear on the suffix. Their custom `block_assembler.message` is 1st.

What about this

```
block_assembler.message_options: {
  embed_client_version: bool, // default is true
}
```

**Comment by zhangsoledad** [comment]
> > > I don't want the user to set this parameter during init, if they want to remove the message_prefix, they need to edit ckb.toml and set it to "0x".
> > > How about adding a commented out line in the generated ckb.toml file?
> > > ```
> > > # A message prefix used to identify the miner client, miner can disable this prefix by setting it to empty hex string: "0x".
> > > # messsage_prefix = "0x"
> > > ```
> > 
> > 
> > The name `message_prefix` is too general. Its purpose is to attach the binary version to cellbase witnesses. It is difficult for me to connect the field's name to its purpose.
> > `cellbase.lock` may want the extra message to appear on the suffix. Their custom `block_assembler.message` is 1st.
> 
> What about this
> 
> ```
> block_assembler.message_options: {
>   embed_client_version: bool, // default is true
> }
> ```

I like this.

**Comment by quake** [comment]
@keroro520 @zhangsoledad change the configuration field name to `use_binary_version_as_message_prefix`, please review again, thanks.

**Review by keroro520 — APPROVED** [review]

**Review by driftluo — APPROVED** [review]

**Review by yangby-cryptape — APPROVED** [review]

**Review by zhangsoledad — APPROVED** [review]

**Comment by quake** [comment]
bors r=keroro520,zhangsoledad,driftluo,yangby-cryptape

**Pull request merged**
