### PR TITLE
refactor: replace non-maintained jsonrpc client

### PR DESCRIPTION
**Pull request by zhangsoledad**
* replace https://crates.io/crates/jsonrpc-client-core
This https://crates.io/crates/jsonrpc-client-core is unruly and still uses tokio-core which is deprecated, 
the maintainers are not around to work on this project. 
https://dev.azure.com/nervosnetwork/ckb/_build/results?buildId=7366
we catch some  `Canceled` error is not being handled elegantly, lead to lock been poisoned.

* singleton http-clinet 
We don't need to instantiate http-clinet for every test-case, every simulate node.

### CODE REVIEW

**Comment by yangby-cryptape** [comment]
bors r=quake,yangby-cryptape

**Comment by zhangsoledad** [comment]
bors r=quake,yangby-cryptape

**Comment by zhangsoledad** [comment]
bors r=quake,yangby-cryptape

**Pull request merged**
