### PR TITLE
refactor: db iterator interface

### PR DESCRIPTION
**Pull request by zhangsoledad**
* get rid of useless lifetimes and unnecessary intermediate conversion code
* property api

### CODE REVIEW

**Comment by u2** [comment]
It's better to add some description.

**Comment by quake** [comment]
bors r=quake,jjyr

**Comment by zhangsoledad** [comment]
bors retry

**Comment by zhangsoledad** [comment]
bors retry

**Comment by zhangsoledad** [comment]
bors retry

**Comment by doitian** [comment]
bors r=doitian,jjyr

**Pull request merged**
