### PR TITLE
fix: trace rpc

### PR DESCRIPTION
**Pull request by zhangsoledad**
addition:
* remove integration tests from root workspace
* fix integration tests logger panic at flush

### CODE REVIEW

**Comment by zhangsoledad** [comment]
bors try

**Comment by doitian** [comment]
Failed because of too many open files in macOS.

**Comment by doitian** [comment]
FYI https://github.com/travis-ci/travis-ci/issues/7728

**Comment by quake** [comment]
default ulimit n is 256 on CI MacOS, it's too small, we may add `ulimit -n 8192` on the script.sh

**Pull request merged**
