### PR TITLE
feat: add rpc dry_run_transaction

### PR DESCRIPTION
**Pull request by keroro520**
* Add rpc `dry_run_transaction`

I place the code inside `rpc/src/module/trace.rs`, together with `trace_transaction`. Since I think `dry_run_transaction` is a kind of interfaces used only at development/testing.

### CODE REVIEW

**Comment by doitian** [comment]
`trace_transaction` is going to be removed 😂. And Trace module is disabled by default. @janx what's your opinion? Should this RPC switch on by default?

**Comment by doitian** [comment]
Let's add it into a new module Experiment, and add it into resource/ckb.toml

**Comment by keroro520** [comment]
> Let's add it into a new module Experiment, and add it into resource/ckb.toml

`Experiment` awesome name.

And, I name 2 new apis `dry_run_transaction` and `_compute_transaction_id` at present, any suggestions ?

**Comment by keroro520** [comment]
Close.
Will open another pr to rewrite it.

**Comment by doitian** [comment]
> And, I name 2 new apis `dry_run_transaction` and `_compute_transaction_id` at present, any suggestions ?

lgtm

**Pull request closed without merging**
