### PR TITLE
Specify `clap` and  `clap_lex`'s version to meet `1.67.1` rust toolchain

### LINKED ISSUE #4136: Some dependencies require higher version of Rust
### Current Behavior

Error when trying to publish the crates:

```
Caused by:
  package `anstream v0.5.0` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.1
=> retrying in 8 seconds ...
    Updating crates.io index
   Packaging ckb-app-config v0.110.2-rc1 (/home/ian/codebase/ckb/util/app-config)
   Verifying ckb-app-config v0.110.2-rc1 (/home/ian/codebase/ckb/util/app-config)
error: failed to verify package tarball

Caused by:
  package `clap_lex v0.5.1` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.1
=> retrying in 16 seconds ...
    Updating crates.io index
   Packaging ckb-app-config v0.110.2-rc1 (/home/ian/codebase/ckb/util/app-config)
   Verifying ckb-app-config v0.110.2-rc1 (/home/ian/codebase/ckb/util/app-config)
error: failed to verify package tarball
```

### Environment

- **CKB version**: v0.110.2-rc1
- **Operating system**: Ubuntu 20.04
- **Arch**: x64
- **Installation**: Built from source

### PR DESCRIPTION
**Pull request by eval-exec**
### What problem does this PR solve?

Latest clap and clap_lex need `1.70.0` rust toolchain. But I have `1.67.1`, so I have to specify clap and clap_lex's version to meet `1.67.1`
Issue Number: close #4136 
Problem Summary:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code ci-runs-only: [ quick_checks,linters ]

Side effects

- None

### Release note 

```release-note
Title Only: Include only the PR title in the release note.
```

### CODE REVIEW

**Comment by eval-exec** [comment]
https://github.com/nervosnetwork/ckb/issues/4136#issuecomment-1703772981

**Comment by doitian** [comment]
I'll cherry pick this to rc branches. For develop, I recommend upgrading rust to 1.71.1

**Comment by eval-exec** [comment]
> I'll cherry pick this to rc branches. For develop, I recommend upgrading rust to 1.71.1

Wait, I think the solution proposed in this GitHub pull request (https://github.com/nervosnetwork/ckb/pull/4138) is better.

**Comment by doitian** [comment]
Cherry picked into rc/v0.110.x and rc/v0.111.x as a temporary workaround.

**Pull request closed without merging**
