### PR TITLE
chore: bump several deps

### PR DESCRIPTION
**Pull request by zhangsoledad**
rocksdb 0.11.0 -> 0.12.0
tokio-sync 0.1.3 -> 0.1.4
proptest 0.9.1 -> 0.9.2

### CODE REVIEW

**Comment by zhangsoledad** [comment]
bors try

**Comment by doitian** [comment]
Please add a config in `bors.toml` in this PR.

```
timeout_sec = 14400
```

Refs https://forum.bors.tech/t/bors-keeps-timing-out/87

**Pull request merged**
