### PR TITLE
feat: tx_pool_info include tip hash

### PR DESCRIPTION
**Pull request by keroro520**
The state of the transaction pool is related to the chain tip. So attaching `tip_hash` and `tip_number` into `TxPoolInfo` which returns by RPC `tx_pool_info` makes it more rigorous.

### CODE REVIEW

**Comment by quake** [comment]
LGTM, please resolve CI fmt issue.

**Comment by doitian** [comment]
bors r=quake,doitian

**Comment by doitian** [comment]
bors r=quake,doitian

**Comment by quake** [comment]
bors r=quake,doitian

**Pull request merged**
