### PR TITLE
feat: record recent reject

### PR DESCRIPTION
**Pull request by zhangsoledad**
### What is changed and how it works?

Proposal: https://talk.nervos.org/t/rfc-ckb-better-support-to-query-transaction-status/6043

### Check List 

Tests 

- Unit test
  db/src/tests/db_with_ttl.rs
  tx-pool/src/component/recent_reject.rs
- Integration test
  test/src/specs/tx_pool/different_txs_with_same_input.rs

Side effects

- Backward compatibility
  * The new configuration has default value if not provided, it‘s compatible.
  * No migration required.

### Release note 

```release-note
Title Only: Include only the PR title in the release note.
```

---
This change is [Reviewable](https://reviewable.io/reviews/nervosnetwork/ckb/3029)

### CODE REVIEW

**Review by chanhsu001 — APPROVED** [review]
looks good to me, except TTL part of db(not familiar with it).

**Review by driftluo — APPROVED** [review]

**Review by doitian — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nervosnetwork/ckb/3029)* status: all files reviewed, 7 unresolved discussions (waiting on @zhangsoledad)

___
*[rpc/README.md, line 4184 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgQCAw6kM3TTdE52wa:-MjgKJyB8owYOSsHe3NJ:beaea1b) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/rpc/README.md#L4184)):*
> ```Markdown
> *   Status "proposed". The transaction is in the pool and has been proposed.
> *   Status "committed". The transaction has been committed to the canonical chain.
> *   Status "Unknown". The node has not seen the transaction, or it should be rejected but was cleared due to storage limitations.
> ```

Please keep it consistent: Status "unknown"
___
*[rpc/README.md, line 4185 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgQHv47BIw_ejzYCEB:-MjgQHv47BIw_ejzYCEC:b-u0w8vn) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/rpc/README.md#L4185)):*
> ```Markdown
> *   Status "committed". The transaction has been committed to the canonical chain.
> *   Status "Unknown". The node has not seen the transaction, or it should be rejected but was cleared due to storage limitations.
> *   Status "Rejected". The transaction has been recently removed from the pool. Due to storage limitations, the node can only hold the most recently removed transactions.
> ```

Please keep it consistent: Status "rejected"
___
*[rpc/README.md, line 4487 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgPn_15wHDaEnfGzFh:-MjgPn_15wHDaEnfGzFi:b-t4yaq0) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/rpc/README.md#L4487)):*
> allowed values: "pending", "proposed" and "committed".

Outdated document
___
*[tx-pool/src/component/recent_reject.rs, line 78 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgRen45YmwF-y1CMFj:-MjgRen7EKhbmz6OYHOF:bp23h9) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/tx-pool/src/component/recent_reject.rs#L78)):*
> ```XML
> 
>     fn shrink(&mut self) -> Result<u64, AnyError> {
>         self.db.drop_cf(SHRINK_SHARD)?;
> ```

Why always drop the first shard?
___
*[util/jsonrpc-types/src/blockchain.rs, line 592 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgRreB6HQHNUX1PKxD:-MjgRreB6HQHNUX1PKxE:b-h46z85) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/util/jsonrpc-types/src/blockchain.rs#L592)):*
> ```XML
>     /// Status "committed". The transaction has been committed to the canonical chain.
>     Committed,
>     /// Status "Unknown". The node has not seen the transaction,
> ```

Suggest change: `Status "unknown"`
___
*[util/jsonrpc-types/src/blockchain.rs, line 595 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgRwZD7wuk9OLnS4Fj:-MjgRwZD7wuk9OLnS4Fk:b7p5se1) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/util/jsonrpc-types/src/blockchain.rs#L595)):*
> ```XML
>     /// or it should be rejected but was cleared due to storage limitations.
>     Unknown,
>     /// Status "Rejected". The transaction has been recently removed from the pool.
> ```

Suggest change: `Status "rejected"`
___
*[util/jsonrpc-types/src/blockchain.rs, line 603 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgRzij8OMCzs3mPCCS:-MjgRzin-CD71Km9Pq4P:b-wsu8s3) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/util/jsonrpc-types/src/blockchain.rs#L603)):*
> ```XML
> #[derive(Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Debug)]
> pub struct TxStatus {
>     /// The transaction status, allowed values: "pending", "proposed" and "committed".
> ```

Outdated

**Review by zhangsoledad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nervosnetwork/ckb/3029)* status: 21 of 27 files reviewed, 6 unresolved discussions (waiting on @doitian)

___
*[rpc/README.md, line 4184 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgQCAw6kM3TTdE52wa:-MjifPU51Yfn869GAKFf:b-896fix) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/rpc/README.md#L4184)):*
<details><summary><i>Previously, doitian (ian) wrote…</i></summary><blockquote>

Please keep it consistent: Status "unknown"
</blockquote></details>

Done.
___
*[rpc/README.md, line 4185 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgQHv47BIw_ejzYCEB:-MjifPwM7pU2QNKUGAW1:b-896fix) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/rpc/README.md#L4185)):*
<details><summary><i>Previously, doitian (ian) wrote…</i></summary><blockquote>

Please keep it consistent: Status "rejected"
</blockquote></details>

Done.
___
*[rpc/README.md, line 4487 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgPn_15wHDaEnfGzFh:-MjifQSE8Iwm0nbyVhOW:b-896fix) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/rpc/README.md#L4487)):*
<details><summary><i>Previously, doitian (ian) wrote…</i></summary><blockquote>

> allowed values: "pending", "proposed" and "committed".

Outdated document
</blockquote></details>

Done.
___
*[tx-pool/src/component/recent_reject.rs, line 78 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgRen45YmwF-y1CMFj:-Mjifl2R7U7fvteaBt4H:b-vc37hf) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/tx-pool/src/component/recent_reject.rs#L78)):*
<details><summary><i>Previously, doitian (ian) wrote…</i></summary><blockquote>

Why always drop the first shard?
</blockquote></details>


Change to random
___
*[util/jsonrpc-types/src/blockchain.rs, line 592 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgRreB6HQHNUX1PKxD:-Mjig39dE_IqlRovHnhA:b-896fix) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/util/jsonrpc-types/src/blockchain.rs#L592)):*
<details><summary><i>Previously, doitian (ian) wrote…</i></summary><blockquote>

Suggest change: `Status "unknown"`
</blockquote></details>

Done.
___
*[util/jsonrpc-types/src/blockchain.rs, line 595 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgRwZD7wuk9OLnS4Fj:-Mjig3_D8Q38ruDU9_Fa:b-896fix) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/util/jsonrpc-types/src/blockchain.rs#L595)):*
<details><summary><i>Previously, doitian (ian) wrote…</i></summary><blockquote>

Suggest change: `Status "rejected"`
</blockquote></details>

Done.
___
*[util/jsonrpc-types/src/blockchain.rs, line 603 at r1](https://reviewable.io/reviews/nervosnetwork/ckb/3029#-MjgRzij8OMCzs3mPCCS:-Mjig3uF60ld_NyxyQaE:b-896fix) ([raw file](https://github.com/nervosnetwork/ckb/blob/d1be2a1b9946b3b42b6e601a381ee000643e3092/util/jsonrpc-types/src/blockchain.rs#L603)):*
<details><summary><i>Previously, doitian (ian) wrote…</i></summary><blockquote>

Outdated
</blockquote></details>

Done.

**Review by doitian — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nervosnetwork/ckb/3029)* status: 23 of 27 files reviewed, 6 unresolved discussions (waiting on @doitian)

**Review by doitian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nervosnetwork/ckb/3029)* status: 23 of 27 files reviewed, all discussions resolved (waiting on @doitian)

**Review by doitian — APPROVED** [review]

**Comment by yangby-cryptape** [comment]
bors merge=chanhsu001,driftluo,doitian

**Pull request merged**
