### PR TITLE
[test]: dev disable system-cell cache

### PR DESCRIPTION
**Pull request by zhangsoledad**

### CODE REVIEW

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 479
  - CKB Version: 9dcdc1d97a072707797303b4e584636185b01dbe
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: In2Out2
  - CKB Logger Filter: info,ckb=debug

**Comment by zhangsoledad** [comment]
sync-test

**Comment by nervos-bot-user** [comment]
#### Sync Test Result
  - CKB Version: 9dcdc1d97a072707797303b4e584636185b01dbe
  - Instance Region: us-west-1
  - Sync Start: 2021-02-24 08:47:11
  - Sync End: 2021-02-24 10:49:27
  - Sync Height: 3861087
  - Sync Speed: 526 blocks/s

**Pull request closed without merging**
