### PR TITLE
perf: add more cache in store to speed up reward calculation

### PR DESCRIPTION
**Pull request by u2**

### CODE REVIEW

**Comment by u2** [comment]
#1123

**Comment by keroro520** [comment]
How much the performance improvement after caching these items?

**Comment by u2** [comment]
Have not found a way to test.

**Comment by doitian** [comment]
@nervos-bot dummy ci b9867ad2144d1b8ac368c6a8304e8b3c8245bc8a

**Comment by doitian** [comment]
@quake @keroro520 can we plan a bench on this? This PR has been stale for a long time.

**Comment by doitian** [comment]
Does it improve the `ckb prof` result?

**Comment by doitian** [comment]
Waiting for @zhangsoledad to fix the bench `process_block` and add another bench which runs the 2-ins 2-outs secp256k1 transactions.

**Comment by u2** [comment]
After adding https://github.com/nervosnetwork/ckb/pull/1128/files#diff-65e0871e65c7b9fa5eb3827ae3a6a9b5R144 back, `test tests::synchronizer::basic_sync ... test tests::synchronizer::basic_sync has been running for over 60 seconds
`. I think there was a dead lock.

**Comment by u2** [comment]
Running /home/u2/nervos/ckb/target/release/deps/process_block-591205486a83a09a
main_branch/100         time:   [1.0374 s 1.0821 s 1.1228 s]                             
                        change: [-4.0702% +1.7134% +7.7907%] (p = 0.60 > 0.05)
                        No change in performance detected.
main_branch/200         time:   [1.8524 s 1.8768 s 1.9247 s]                             
                        change: [-15.783% -10.508% -5.1408%] (p = 0.00 < 0.05)
                        Performance has improved.
main_branch/500         time:   [5.0150 s 5.2366 s 5.5066 s]                             
                        change: [-10.782% -6.7164% -1.8504%] (p = 0.01 < 0.05)
                        Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
main_branch/1000        time:   [9.8844 s 10.270 s 10.802 s]                              
                        change: [-15.308% -10.564% -5.6560%] (p = 0.00 < 0.05)
                        Performance has improved.

side_branch/100         time:   [1.6329 ms 1.9874 ms 2.3899 ms]                          
                        change: [-53.894% -44.880% -32.568%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe
side_branch/200         time:   [2.4981 ms 2.8895 ms 3.1252 ms]                          
                        change: [-52.736% -41.416% -26.168%] (p = 0.00 < 0.05)
                        Performance has improved.
side_branch/500         time:   [5.2691 ms 6.3112 ms 7.0220 ms]                          
                        change: [-43.547% -30.676% -14.646%] (p = 0.01 < 0.05)
                        Performance has improved.
side_branch/1000        time:   [10.193 ms 12.209 ms 13.509 ms]                           
                        change: [-31.344% -17.739% -1.6657%] (p = 0.07 > 0.05)
                        No change in performance detected.

switch_fork/100         time:   [130.21 ms 135.91 ms 142.24 ms]                          
                        change: [-26.109% -16.249% -5.9496%] (p = 0.02 < 0.05)
                        Performance has improved.
switch_fork/200         time:   [303.36 ms 310.62 ms 322.07 ms]                          
                        change: [-24.805% -14.314% -3.4355%] (p = 0.03 < 0.05)
                        Performance has improved.
switch_fork/500         time:   [1.1473 s 1.2687 s 1.4011 s]                             
                        change: [-26.011% -16.985% -7.4736%] (p = 0.01 < 0.05)
                        Performance has improved.
switch_fork/1000        time:   [3.4746 s 3.6069 s 3.7165 s]                              
                        change: [-25.983% -20.527% -14.845%] (p = 0.00 < 0.05)
                        Performance has improved.

**Pull request merged**
