### PR TITLE
resumable rpc tx submit

### PR DESCRIPTION
**Pull request by zhangsoledad**
### What is changed and how it works?

Previously, the submit_tx rpc not using resume mode.
This PR proposal turned submit_tx rpc to resume mode, to keep the same behavior as the relay when accepting transactions,  make rpc to do pre-check to avoid unexpected bugs leading to ban.

### Check List 

Tests 

- Unit test

### Release note 

```release-note
Title Only: Include only the PR title in the release note.
```

### CODE REVIEW

**Review by yangby-cryptape — APPROVED** [review]

**Review by driftluo — APPROVED** [review]

**Comment by zhangsoledad** [comment]
bors r=driftluo,yangby-cryptape

**Comment by zhangsoledad** [comment]
bors retry

**Comment by zhangsoledad** [comment]
bors retry

**Comment by zhangsoledad** [comment]
bors retry

**Pull request merged**
