### PR TITLE
doc: correct typo on anchor in RPC README.md

### PR DESCRIPTION
**Pull request by fjchen7**
### What is changed and how it works?

Correct typo in RPC README.md

### Release note 

```release-note
None: Exclude this PR from the release note.
```

### CODE REVIEW

**Comment by zhangsoledad** [comment]
Thank you for informing us of this issue. The rpc's documentation is automatically generated based on comments, so we don't modify the documentation directly, but rather correct the problematic comments and then regenerate the documentation.
If you'd like to continue contributing, you can correct the comments `rpc/src/module/chain.rs#654L` and then run `make gen-rpc-doc` in the ckb root directory.

**Comment by fjchen7** [comment]
I have pushed a new commit to modify the code.

**Review by doitian — APPROVED** [review]

**Comment by doitian** [comment]
bors r

**Pull request merged**
