### PR TITLE
refine runs-on label

### PR DESCRIPTION
**Pull request by liya2017**
refine runs-on label to using common label such `Linux` and `macOS`

### CODE REVIEW

**Comment by nervos-bot-user** [comment]
Can one of the admins verify this patch?

**Comment by nervos-bot-user** [comment]
Can one of the admins verify this patch?

**Comment by liya2017** [comment]
Liners failed on M1 since need the PR https://github.com/nervosnetwork/ckb/pull/2732.Can we follow the travis CI status?

**Comment by doitian** [comment]
Please rebase

**Pull request closed without merging**
