### PR TITLE
refactory cell storage

### PR DESCRIPTION
**Pull request by zhangsoledad**

### CODE REVIEW

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 369.02
  - Samples Count: 50
  - CKB Version: bbe6394b8c24c476c513a9cea3fdf80047162051
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Comment by zhangsoledad** [comment]
benchmark

**Comment by nervos-bot-user** [comment]
#### Benchmark Result
  - TPS: 359.06
  - Samples Count: 51
  - CKB Version: 9a76fe3643a94dc6000b5caf0ba96d9ec896a643
  - Instance Type: c5.xlarge
  - Instances Count: 3
  - Bench Type: 2in2out
  - CKB Logger Filter: info,ckb=debug

**Pull request merged**
