### PR TITLE
feat: Log more sync and relay metrics

### PR DESCRIPTION
**Pull request by keroro520**
Add some metrics:

* chain:
  - blocks chain tip number
  - headers chain tip number

* sync/relay
  - in/out messages
  - blocks_in_flight state

* get_ancestor
  - steps, elpased, base_number, target_number

### CODE REVIEW

**Comment by doitian** [comment]
bors r=doitian,driftluo

**Comment by doitian** [comment]
bors retry

**Comment by doitian** [comment]
@keroro520 please resolve conflicts

**Comment by doitian** [comment]
conflict again

**Comment by driftluo** [comment]
bors r=doitian,driftluo

**Pull request merged**
