### PR TITLE
refactor: replace metric macros by metrics service

### PR DESCRIPTION
**Pull request by yangby-cryptape**
Remove the old metric macros.

### CODE REVIEW

**Comment by doitian** [comment]
Any example to show off the exported metrics?

**Comment by doitian** [comment]
Approved but waiting for rebase

**Comment by keroro520** [comment]
> Any example to show off the exported metrics?

Another PR https://github.com/nervosnetwork/ckb/pull/2200 contains enough examples.

**Comment by keroro520** [comment]
> > Any example to show off the exported metrics?
> 
> ~~Another PR #2200 contains enough examples~~

I Misunderstood..

**Comment by yangby-cryptape** [comment]
Ready for review!

**Comment by yangby-cryptape** [comment]
bors r=zhangsoledad,doitian

**Comment by yangby-cryptape** [comment]
bors r=zhangsoledad,doitian

**Comment by doitian** [comment]
bors retry

**Pull request merged**
