### PR TITLE
ci: ci not run last job in the run_job list

### PR DESCRIPTION
**Pull request by liya2017**
### What problem does this PR solve?

CI not run last job in the runs_only list , since the  in the last job contains a space, fix it

### Check List

Tests

- No code ci-runs-only: [ quick_checks,linters ]

### Release note

```release-note
None: Exclude this PR from the release note.
```

### CODE REVIEW

**Comment by yangby-cryptape** [comment]
- Here is another line which is same as the current line you update in this PR.

  - If this line is required to update?

    https://github.com/nervosnetwork/ckb/blob/fb82ae14d9552d9025778323011900edaf5ed692/.github/actions/ci_prologue/ci_prologue.sh#L11

  - Another question about this line: is it unnecessary? Can we just remove this line?

- The indentation of `if ... fi` block is not right.

  https://github.com/nervosnetwork/ckb/blob/fb82ae14d9552d9025778323011900edaf5ed692/.github/actions/ci_prologue/ci_prologue.sh#L10-L16

- If you just want to remove the newline in the variable `LINE`, try:

  ```bash
  LINE=$(echo -n "ci_${LINE}")
  # or
  LINE=$(printf "ci_${LINE}")
  # or
  LINE="ci_$(echo -n "${LINE}")"
  # or
  LINE="ci_$(printf "${LINE}")"
  ```

**Comment by liya2017** [comment]
> * If this line is required to update?
>   https://github.com/nervosnetwork/ckb/blob/fb82ae14d9552d9025778323011900edaf5ed692/.github/actions/ci_prologue/ci_prologue.sh#L11
> * Another question about this line: is it unnecessary? Can we just remove this line?
>   There should be no newline in the variable `LINE` if not `echo` it.

It's required o update and can not remove it, should remove space in variable `LINE`. 
The space contains in  the  last job in the runs_only list, so remove it.

**Review by doitian — APPROVED** [review]

**Review by zhangsoledad — APPROVED** [review]

**Comment by liya2017** [comment]
bors r=doitian ,zhangsoledad

**Comment by zhangsoledad** [comment]
https://github.com/nervosnetwork/ckb/pull/3220

**Comment by zhangsoledad** [comment]
bors retry

**Pull request merged**
