### PR TITLE
fix(reset-data): the argument `--network-peer-store` couldn't work

### PR DESCRIPTION
**Pull request by yangby-cryptape**
### What problem does this PR solve?

- The argument `--network-peer-store` for the sub-command `reset-data` couldn't work.

  Because the path of `network/peer-store` is a directory but using a method which removes files to delete it.

- Return code is `0` when has errors.

- Prompt to remove a empty path.

### Check List 

Tests

- Manual test (add detailed scripts or steps below)

  - `ckb init --chain dev -C dev`

  - Check 1:

    - `ckb reset-data -C dev`: returns `0` immediately without prompt.

  - `ckb run -C dev` and `Ctrl-C` after 10 seconds.

  - Check 2:

    - `ls dev/data/network/peer_store`: the directory should exists.

    -  `ckb reset-data -C dev --force --network-peer-store`: returns `0` immediately without prompt.

    - `ls dev/data/network/peer_store`: the directory should be removed.

  - `rm dev/data/network/secret_key`

  - `mkdir dev/data/network/secret_key`

  - Check 3:

    -  `ckb reset-data -C dev --force --network-secret-key`: returns `>0` immediately without prompt.

### Release note

```release-note
Title Only: Include only the PR title in the release note.
```

### CODE REVIEW

**Comment by doitian** [comment]
This PR requires the test check list section in the PR template:

```
Tests <!-- At least one of them must be included. -->

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code (skip ci)
```

**Comment by yangby-cryptape** [comment]
> This PR requires the test check list section in the PR template:
> 
> ```
> Tests 
> 
> - Unit test
> - Integration test
> - Manual test (add detailed scripts or steps below)
> - No code (skip ci)
> ```

DONE!

**Review by doitian — APPROVED** [review]

**Comment by doitian** [comment]
@zhangsoledad @liya2017 please review

**Review by driftluo — APPROVED** [review]

**Comment by yangby-cryptape** [comment]
bors merge=doitian,driftluo

**Pull request merged**
